import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import SearchableSelect from "@/components/shared/SearchableSelect";
import ChildRowModal from "./ChildRowModal";
import { today } from "./lifecycleConfig";

const noQuickCreate=["Employee","Student","User","Account"];
function ReadOnlyValue({value}){return <div className="flex min-h-[40px] items-center rounded-md bg-muted px-3 py-2 text-sm font-medium text-muted-foreground">{value===undefined||value===null||value===""?"—":String(value)}</div>}
function Input({field,value,onChange,options,disabled}){
  if(field.type==="link") return <SearchableSelect value={value||""} onChange={onChange} options={options||[]} displayField={field.displayField} showId={field.showId} label={field.label} placeholder={`Search ${field.label.toLowerCase()}...`} disabled={disabled} linkedDoctype={noQuickCreate.includes(field.doctype)?null:field.doctype}/>;
  if(field.type==="select") return <select className="input" value={value||""} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Select...</option>{field.options.map(x=><option key={x}>{x}</option>)}</select>;
  if(field.type==="check") return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(Number(value))} disabled={disabled} onChange={e=>onChange(e.target.checked?1:0)}/> Yes</label>;
  if(field.type==="textarea") return <textarea className="input" rows={4} style={{height:"auto"}} value={value||""} disabled={disabled} onChange={e=>onChange(e.target.value)}/>;
  const type={date:"date",datetime:"datetime-local",number:"number",email:"email"}[field.type]||"text";
  return <input className="input" type={type} min={field.min} max={field.max} value={value||""} disabled={disabled} onChange={e=>onChange(e.target.value)}/>;
}

export default function LifecycleForm({config,doc,onSave}){
  const editing=Boolean(doc); const initial=useMemo(()=>Object.fromEntries(config.fields.map(field=>[field.name,field.default==="today"?today():field.default||""])),[config]);
  const[form,setForm]=useState(initial),[saving,setSaving]=useState(false),[options,setOptions]=useState({}),[modal,setModal]=useState(null);
  useEffect(()=>{if(doc){const next={...initial,...doc}; for(const table of config.tables||[]) next[table.name]=doc[table.name]||[]; setForm(next)}},[doc,initial,config.tables]);
  useEffect(()=>{const doctypes=[...new Set([...config.fields,...(config.tables||[]).flatMap(t=>t.fields)].filter(f=>f.type==="link").map(f=>f.doctype))]; if(!config.service.getLookupOptions)return; Promise.all(doctypes.map(async doctype=>[doctype,await config.service.getLookupOptions(doctype)])).then(rows=>setOptions(Object.fromEntries(rows))).catch(()=>setOptions({}));},[config]);
  const setField=(name,value)=>setForm(old=>({...old,[name]:value}));
  async function changeField(field,value){setField(field.name,value); try{
    if(config.employeeField===field.name&&config.service.getEmployeeDetails){if(!value){setForm(old=>({...old,[field.name]:"",employee_name:"",department:"",company:"",designation:"",employee_grade:"",grade:"",holiday_list:""}));}else{const details=await config.service.getEmployeeDetails(value);setForm(old=>({...old,[field.name]:value,...details}));}}
    if(field.name==="employee_onboarding_template"&&value&&config.service.getTemplate){const template=await config.service.getTemplate(value);setForm(old=>({...old,employee_onboarding_template:value,company:template.company||old.company,department:template.department||old.department,designation:template.designation||old.designation,employee_grade:template.employee_grade||old.employee_grade,activities:template.activities||[]}));}
    if(field.name==="training_event"&&value&&config.service.getTrainingEvent){const event=await config.service.getTrainingEvent(value);setForm(old=>({...old,training_event:value,event_name:event.event_name||old.event_name,course:event.course||old.course,trainer_name:event.trainer_name||old.trainer_name,...(config.title==="Training Result"?{employees:(event.employees||[]).map(row=>({employee:row.employee,employee_name:row.employee_name,department:row.department}))}:{})}));}
  }catch{/* linked fetches are conveniences; server validation remains authoritative */}}
  async function submit(e){e.preventDefault(); for(const field of config.fields){if(field.required&&!form[field.name])return toast.error(`${field.label} is required`)} setSaving(true);try{await onSave(form)}finally{setSaving(false)}}
  function saveRow(row){const table=modal.table,index=modal.index; const required=table.fields.find(field=>field.required&&!row[field.name]); if(required)return toast.error(`${required.label} is required`); setForm(old=>({...old,[table.name]:index===null?[...(old[table.name]||[]),row]:(old[table.name]||[]).map((item,i)=>i===index?row:item)}));setModal(null)}
  const sections=[]; for(const field of config.fields){const section=field.section||"Details";let found=sections.find(x=>x.label===section);if(!found){found={label:section,fields:[]};sections.push(found)}found.fields.push(field)}
  return <form onSubmit={submit}>{sections.map(section=><section key={section.label}><div className="panel-head"><div className="panel-title">{section.label}</div></div><div className="grid-form" style={{padding:"10px 20px 26px"}}>{section.fields.map(field=><div className="field" key={field.name} style={field.full?{gridColumn:"1 / -1"}:undefined}><label className="label">{field.label}{field.required&&<span style={{color:"var(--danger)",marginLeft:3}}>*</span>}</label>{field.readOnly||(editing&&field.immutable)?<ReadOnlyValue value={form[field.name]}/>:<Input field={field} value={form[field.name]} onChange={value=>changeField(field,value)} options={options[field.doctype]} disabled={false}/>}</div>)}</div></section>)}{(config.tables||[]).filter(table=>!table.optional||doc?.education_field||form[table.name]?.length).map(table=><section key={table.name}><div className="panel-head"><div className="panel-title">{table.label}</div><button type="button" className="btn btn-secondary" onClick={()=>setModal({table,index:null,row:null})}><Plus size={14}/> Add Row</button></div><div style={{padding:"10px 20px 26px",overflowX:"auto"}}><table className="tbl"><thead><tr>{table.fields.slice(0,4).map(x=><th key={x.name}>{x.label}</th>)}<th/></tr></thead><tbody>{(form[table.name]||[]).map((row,index)=><tr key={index}>{table.fields.slice(0,4).map(x=><td key={x.name}>{x.type==="check"?(Number(row[x.name])?"Yes":"No"):(row[x.name]||"—")}</td>)}<td><div className="flex gap-1"><button type="button" className="btn btn-ghost" onClick={()=>setModal({table,index,row})}><Pencil size={14}/></button><button type="button" className="btn btn-ghost" onClick={()=>setForm(old=>({...old,[table.name]:(old[table.name]||[]).filter((_,i)=>i!==index)}))}><Trash2 size={14}/></button></div></td></tr>)}{!(form[table.name]||[]).length&&<tr><td colSpan={table.fields.slice(0,4).length+1} className="text-sm text-muted-foreground">No rows added.</td></tr>}</tbody></table></div></section>)}<div className="flex justify-end gap-2 p-5"><button type="button" className="btn btn-secondary" onClick={()=>history.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?"Saving...":editing?`Update ${config.title}`:`Create ${config.title}`}</button></div><ChildRowModal open={Boolean(modal)} onClose={()=>setModal(null)} onSave={saveRow} fields={modal?.table.fields||[]} row={modal?.row} optionMap={options}/></form>;
}
