import * as grievanceType from "@/services/employee-lifecycle/grievanceTypeService";
import * as trainingProgram from "@/services/employee-lifecycle/trainingProgramService";
import * as onboardingTemplate from "@/services/employee-lifecycle/employeeOnboardingTemplateService";
import * as onboarding from "@/services/employee-lifecycle/employeeOnboardingService";
import * as skillMap from "@/services/employee-lifecycle/employeeSkillMapService";
import * as grievance from "@/services/employee-lifecycle/employeeGrievanceService";
import * as trainingEvent from "@/services/employee-lifecycle/trainingEventService";
import * as trainingFeedback from "@/services/employee-lifecycle/trainingFeedbackService";
import * as trainingResult from "@/services/employee-lifecycle/trainingResultService";

const f=(name,label,type="text",extra={})=>({name,label,type,...extra});
const employee=f("employee","Employee","link",{doctype:"Employee",displayField:"employee_name",showId:true});
const raisedBy=f("raised_by","Raised By","link",{doctype:"Employee",displayField:"employee_name",showId:true,required:true});
const activities={name:"activities",label:"Activities",fields:[f("activity_name","Activity Name","text",{required:true}),f("role","Role","link",{doctype:"Role"}),f("user","User","link",{doctype:"User",displayField:"full_name",showId:true}),f("begin_on","Begin On (Days)","number"),f("duration","Duration (Days)","number"),f("task_weight","Task Weight","number"),f("required_for_employee_creation","Required for Employee Creation","check"),f("description","Description","textarea")]};
const employeeRows={name:"employees",label:"Employees",fields:[employee,f("status","Status","select",{options:["Open","Invited","Completed","Feedback Submitted"]}),f("attendance","Attendance","select",{options:["Present","Absent"]}),f("is_mandatory","Is Mandatory","check")]};

export const CONFIG={
  "grievance-type":{title:"Grievance Type",plural:"Grievance Types",service:grievanceType,titleField:"name",list:["name","description"],fields:[f("name","Grievance Type","text",{required:true,immutable:true}),f("description","Description","textarea")]},
  "training-program":{title:"Training Program",plural:"Training Programs",service:trainingProgram,titleField:"training_program",statusField:"status",statuses:["Scheduled","Completed","Cancelled"],connectionItems:[{key:"training_events",label:"Training Events",path:"/dashboard/training-event",filter:"training_program"}],list:["training_program","company","trainer_name","status"],fields:[f("training_program","Training Program","text",{required:true,immutable:true}),f("status","Status","select",{options:["Scheduled","Completed","Cancelled"],default:"Scheduled"}),f("company","Company","link",{doctype:"Company",required:true}),f("trainer_name","Trainer Name"),f("trainer_email","Trainer Email","email"),f("supplier","Supplier","link",{doctype:"Supplier"}),f("contact_number","Contact Number"),f("description","Description","textarea",{required:true,full:true})]},
  "employee-onboarding-template":{title:"Employee Onboarding Template",plural:"Employee Onboarding Templates",service:onboardingTemplate,titleField:"title",connectionItems:[{key:"employee_onboardings",label:"Employee Onboarding",path:"/dashboard/employee-onboarding",filter:"employee_onboarding_template"}],list:["title","company","department","designation"],fields:[f("title","Title","text",{required:true}),f("company","Company","link",{doctype:"Company"}),f("department","Department","link",{doctype:"Department"}),f("designation","Designation","link",{doctype:"Designation"}),f("employee_grade","Employee Grade","link",{doctype:"Employee Grade"})],tables:[activities]},
  "employee-onboarding":{title:"Employee Onboarding",plural:"Employee Onboarding",service:onboarding,titleField:"employee_name",submittable:true,statusField:"boarding_status",statuses:["Pending","In Process","Completed"],employeeField:"employee",list:["employee_name","date_of_joining","department","boarding_status"],fields:[f("job_applicant","Job Applicant","link",{doctype:"Job Applicant",required:true}),f("job_offer","Job Offer","link",{doctype:"Job Offer",required:true}),f("employee_onboarding_template","Employee Onboarding Template","link",{doctype:"Employee Onboarding Template"}),employee,f("employee_name","Employee Name","text",{required:true,readOnly:true}),f("company","Company","link",{doctype:"Company",required:true,readOnly:true}),f("department","Department","link",{doctype:"Department",readOnly:true}),f("designation","Designation","link",{doctype:"Designation",readOnly:true}),f("employee_grade","Employee Grade","link",{doctype:"Employee Grade",readOnly:true}),f("holiday_list","Holiday List","link",{doctype:"Holiday List"}),f("date_of_joining","Date of Joining","date",{required:true}),f("boarding_begins_on","Onboarding Begins On","date",{required:true}),f("notify_users_by_email","Notify Users by Email","check")],tables:[{...activities,label:"Boarding Activities"}]},
  "employee-skill-map":{title:"Employee Skill Map",plural:"Employee Skill Maps",service:skillMap,titleField:"employee_name",list:["employee_name","employee","designation"],employeeField:"employee",fields:[employee,f("employee_name","Employee Name","text",{readOnly:true}),f("company","Company","text",{readOnly:true}),f("department","Department","text",{readOnly:true}),f("designation","Designation","text",{readOnly:true})],tables:[{name:"employee_skills",label:"Employee Skills",fields:[f("skill","Skill","link",{doctype:"Skill",required:true}),f("proficiency","Proficiency","number",{required:true,min:1,max:5}),f("evaluation_date","Evaluation Date","date")]},{name:"employee_educations",label:"Employee Education",optional:true,fields:[f("school_univ","School / University","textarea"),f("qualification","Qualification"),f("level","Level","select",{options:["Graduate","Post Graduate","Under Graduate"]}),f("year_of_passing","Year of Passing","number"),f("class_per","Class / Percentage"),f("maj_opt_subj","Major / Optional Subjects","textarea")]}]},
  "employee-grievance":{title:"Employee Grievance",plural:"Employee Grievances",service:grievance,titleField:"subject",submittable:true,statusField:"status",statuses:["Open","Investigated","Resolved","Invalid"],employeeField:"raised_by",list:["subject","employee_name","grievance_type","date","status"],fields:[f("subject","Subject","text",{required:true}),raisedBy,f("employee_name","Employee Name","text",{readOnly:true}),f("company","Company","text",{readOnly:true}),f("department","Department","text",{readOnly:true}),f("designation","Designation","text",{readOnly:true}),f("reports_to","Reports To","text",{readOnly:true}),f("date","Date","date",{required:true,default:"today"}),f("status","Status","select",{required:true,options:["Open","Investigated","Resolved","Invalid"],default:"Open"}),f("grievance_type","Grievance Type","link",{doctype:"Grievance Type",required:true}),f("grievance_against_party","Grievance Against Party","select",{required:true,options:["Company","Department","Employee Group","Employee Grade","Employee"]}),f("grievance_against","Grievance Against", "text",{required:true}),f("associated_document_type","Associated Document Type","link",{doctype:"DocType"}),f("associated_document","Associated Document"),f("description","Description","textarea",{required:true,full:true,section:"Grievance Details"}),f("cause_of_grievance","Cause of Grievance","textarea",{full:true,section:"Investigation Details"}),f("resolved_by","Resolved By","link",{doctype:"User",displayField:"full_name",showId:true,section:"Resolution Details"}),f("resolution_date","Resolution Date","date"),f("employee_responsible","Employee Responsible","link",{doctype:"Employee",displayField:"employee_name",showId:true}),f("resolution_detail","Resolution Details","textarea",{full:true})]},
  "training-event":{title:"Training Event",plural:"Training Events",service:trainingEvent,titleField:"event_name",submittable:true,statusField:"event_status",statuses:["Scheduled","Completed","Cancelled"],connectionItems:[{key:"training_feedback",label:"Training Feedback",path:"/dashboard/training-feedback",filter:"training_event"},{key:"training_results",label:"Training Results",path:"/dashboard/training-result",filter:"training_event"}],list:["event_name","training_program","type","location","event_status"],fields:[f("event_name","Event Name","text",{required:true,immutable:true}),f("training_program","Training Program","link",{doctype:"Training Program"}),f("event_status","Event Status","select",{required:true,options:["Scheduled","Completed","Cancelled"],default:"Scheduled"}),f("type","Type","select",{required:true,options:["Seminar","Theory","Workshop","Conference","Exam","Internet","Self-Study"]}),f("level","Level","select",{options:["Beginner","Intermediate","Advance"]}),f("has_certificate","Has Certificate","check"),f("company","Company","link",{doctype:"Company"}),f("trainer_name","Trainer Name", "text",{section:"Trainer Details"}),f("trainer_email","Trainer Email","email"),f("supplier","Supplier","link",{doctype:"Supplier"}),f("contact_number","Contact Number"),f("course","Course", "text",{section:"Schedule"}),f("location","Location","text",{required:true}),f("start_time","Start Time","datetime",{required:true}),f("end_time","End Time","datetime",{required:true}),f("introduction","Introduction","textarea",{required:true,full:true})],tables:[employeeRows]},
  "training-feedback":{title:"Training Feedback",plural:"Training Feedback",service:trainingFeedback,titleField:"employee_name",submittable:true,employeeField:"employee",list:["employee_name","event_name","trainer_name","department"],fields:[employee,f("employee_name","Employee Name","text",{readOnly:true}),f("department","Department","text",{readOnly:true}),f("company","Company","text",{readOnly:true}),f("designation","Designation","text",{readOnly:true}),f("training_event","Training Event","link",{doctype:"Training Event",displayField:"event_name",showId:true,required:true}),f("event_name","Event Name","text",{readOnly:true}),f("course","Course","text",{readOnly:true}),f("trainer_name","Trainer Name","text",{readOnly:true}),f("rating","Rating","number",{min:1,max:5}),f("feedback","Feedback","textarea",{required:true,full:true})]},
  "training-result":{title:"Training Result",plural:"Training Results",service:trainingResult,titleField:"training_event",submittable:true,list:["training_event","docstatus","modified"],fields:[f("training_event","Training Event","link",{doctype:"Training Event",displayField:"event_name",showId:true,required:true})],tables:[{name:"employees",label:"Employee Results",fields:[employee,f("employee_name","Employee Name","text",{readOnly:true}),f("department","Department","text",{readOnly:true}),f("hours","Hours","number"),f("grade","Grade"),f("comments","Comments","textarea")]}]},
};

export const labelize=value=>String(value||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export const today=()=>new Date().toISOString().slice(0,10);
