import { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { EmptyState, PageHeader } from "@/components/shared/OriginalPrimitives";
import Toolbar from "@/components/shared/Toolbar"; import Pager from "@/components/shared/Pager"; import RowActionsMenu from "@/components/shared/RowActionsMenu"; import ConfirmDialog from "@/components/shared/ConfirmDialog";
import { usePagination } from "@/hooks"; import { getErrorMessage } from "@/utils/errors";
import LifecycleStatusBadge from "./LifecycleStatusBadge"; import { labelize } from "./lifecycleConfig";

export default function LifecycleListPage({config,base}){const nav=useNavigate(),[sp]=useSearchParams(),{page,setPage}=usePagination(1),[rows,setRows]=useState([]),[count,setCount]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[target,setTarget]=useState(null);async function load(){try{setLoading(true);const params={page,search};if(config.statusField)params[config.statusField]=status||undefined;for(const key of ["employee","training_event","training_program","employee_onboarding_template"])if(sp.get(key))params[key]=sp.get(key);const result=await config.service.getList(params);setRows(result.rows||[]);setCount(result.count||0)}catch(error){toast.error(getErrorMessage(error))}finally{setLoading(false)}}useEffect(()=>{load();/* eslint-disable-next-line */},[page,search,status,sp.toString()]);async function remove(){try{await config.service.remove(target.name);toast.success(`${config.title} deleted`);setTarget(null);load()}catch(error){toast.error(getErrorMessage(error))}}return <><PageHeader eyebrow="HR · Employee Lifecycle" title={config.plural} sub={loading?"Loading...":`${count} records`} button={<button className="btn btn-primary" onClick={()=>nav(`/dashboard/${base}/new`)}><Plus size={15}/> Add {config.title}</button>}/><Toolbar search={search} onSearch={value=>{setSearch(value);setPage(1)}} filters={config.statusField?[{key:"status",label:"Status",value:status,onChange:value=>{setStatus(value);setPage(1)},options:config.statuses||[]}]:[]}/><div className="panel"><div style={{overflowX:"auto"}}><table className="tbl"><thead><tr>{config.list.map(field=><th key={field}>{labelize(field)}</th>)}<th/></tr></thead><tbody>{rows.map(row=><tr key={row.name} className="cursor-pointer" onClick={()=>nav(`/dashboard/${base}/${encodeURIComponent(row.name)}`)}>{config.list.map(field=><td key={field}>{field===config.statusField?<LifecycleStatusBadge status={row[field]}/>:field==="docstatus"?<LifecycleStatusBadge status={row[field]===1?"Submitted":row[field]===2?"Cancelled":"Draft"}/>:row[field]||"—"}</td>)}<td onClick={event=>event.stopPropagation()}><RowActionsMenu onView={()=>nav(`/dashboard/${base}/${encodeURIComponent(row.name)}`)} onEdit={row.can_edit?()=>nav(`/dashboard/${base}/${encodeURIComponent(row.name)}/edit`):undefined} onDelete={row.can_delete?()=>setTarget(row):undefined}/></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={config.list.length+1}><EmptyState title={`No ${config.plural.toLowerCase()} found`}/></td></tr>}</tbody></table></div><Pager page={page} setPage={setPage} pageSize={20} count={count}/></div><ConfirmDialog open={Boolean(target)} onClose={()=>setTarget(null)} onConfirm={remove} title={`Delete ${target?.name}?`} description="This action cannot be undone. Linked records may prevent deletion." confirmLabel="Delete"/></>}
