import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronRight, Plus, Trash2 } from "lucide-react";
import SearchableSelect from "@/components/shared/SearchableSelect";
import { getEmployeeDepartments, getEmployeeLinkOptions, getEmployeeUsers, getPayrollCostCenters, getReportsTo } from "@/services/hr/employeeService";
import { fmtDate } from "@/utils/format";

const SKIP = new Set(["HTML", "Button"]); const TEXT = new Set(["Text", "Text Editor", "Small Text", "Long Text", "Code"]); const LAYOUT = new Set(["Tab Break", "Section Break", "Column Break"]);
const slug = (value) => String(value || "Overview").toLowerCase().replace(/[^a-z0-9]+/g, "-");
function tabsFor(fields) { const tabs = []; let current = null; for (const field of fields || []) { if (field.fieldtype === "Tab Break") { current = { key: slug(field.fieldname || field.label), label: field.label || "Overview", fields: [] }; tabs.push(current); } else { if (!current) { current = { key: "overview", label: "Overview", fields: [] }; tabs.push(current); } current.fields.push(field); } } return tabs.filter((tab) => tab.fields.some((field) => !field.hidden && !LAYOUT.has(field.fieldtype) && !SKIP.has(field.fieldtype))); }
function sectionsFor(fields) { const sections = []; let section = { key: "main", label: "", collapsible: false, columns: [[]] }; sections.push(section); for (const field of fields || []) { if (field.hidden) continue; if (field.fieldtype === "Section Break") { section = { key: field.fieldname, label: field.label || "", collapsible: Boolean(field.collapsible), columns: [[]] }; sections.push(section); } else if (field.fieldtype === "Column Break") section.columns.push([]); else if (!LAYOUT.has(field.fieldtype) && !SKIP.has(field.fieldtype)) section.columns.at(-1).push(field); } return sections.filter((item) => item.columns.some((column) => column.length)); }
function dependency(field, doc) { if (!field.depends_on) return true; const simple = field.depends_on.match(/^([A-Za-z_]\w*)$/); if (simple) return Boolean(doc[simple[1]]); const truthy = field.depends_on.match(/^eval:\s*!?doc\.([A-Za-z_]\w*)\s*$/); if (truthy) return field.depends_on.includes("!") ? !doc[truthy[1]] : Boolean(doc[truthy[1]]); const equal = field.depends_on.match(/^eval:\s*doc\.([A-Za-z_]\w*)\s*={2,3}\s*["']([^"']+)["']/); if (equal) return String(doc[equal[1]] || "") === equal[2]; return true; }
function shown(field, value) { if (value === null || value === undefined || value === "") return "—"; if ((value === 0 || value === "0") && !["Check", "Int", "Float", "Currency", "Percent"].includes(field.fieldtype)) return "—"; if (field.fieldtype === "Check") return Number(value) ? "Yes" : "No"; if (field.fieldtype === "Date") return fmtDate(value); if (field.fieldtype === "Currency") return Number(value).toLocaleString(); return String(value); }

function LinkControl({ field, value, onChange, disabled, document }) {
  const [options, setOptions] = useState(value ? [{ name: value, display_name: value }] : []); const companyDependent = ["department", "payroll_cost_center"].includes(field.fieldname);
  useEffect(() => { let active = true; if (companyDependent && !document.company) { setOptions(value ? [{ name: value, display_name: value }] : []); return () => { active = false; }; } let request; if (field.fieldname === "department") request = getEmployeeDepartments(document.company); else if (field.fieldname === "payroll_cost_center") request = getPayrollCostCenters(document.company); else if (field.fieldname === "reports_to") request = getReportsTo(document.name); else if (["user_id", "expense_approver", "leave_approver", "shift_request_approver"].includes(field.fieldname)) request = getEmployeeUsers(); else request = getEmployeeLinkOptions(field.options); request.then((rows) => { if (!active) return; const next = rows || []; if (value && !next.some((row) => row.name === value)) next.unshift({ name: value, display_name: value }); setOptions(next); }).catch(() => setOptions(value ? [{ name: value, display_name: value }] : [])); return () => { active = false; }; }, [field.fieldname, field.options, value, document.company, document.name, companyDependent]);
  const displayField = field.options === "Employee" ? "employee_name" : field.options === "User" ? "full_name" : "display_name";
  return <SearchableSelect value={value || ""} onChange={onChange} options={options} displayField={displayField} label={field.label || field.fieldname} placeholder={companyDependent && !document.company ? "Select a company first" : `Search ${field.label || field.fieldname}...`} disabled={disabled || (companyDependent && !document.company)} showId />;
}
function Control({ field, value, onChange, disabled, document }) { if (field.fieldtype === "Link") return <LinkControl field={field} value={value} onChange={onChange} disabled={disabled} document={document} />; if (field.fieldtype === "Select") return <select className="select" value={value ?? ""} disabled={disabled} onChange={(event) => onChange(event.target.value)}>{String(field.options || "").split("\n").map((option, index) => <option key={`${option}-${index}`} value={option}>{option || `Select ${field.label || "value"}`}</option>)}</select>; if (field.fieldtype === "Check") return <label className="flex h-9 items-center gap-2"><input type="checkbox" checked={Boolean(Number(value))} disabled={disabled} onChange={(event) => onChange(event.target.checked ? 1 : 0)} /><span className="text-sm">{Number(value) ? "Yes" : "No"}</span></label>; if (TEXT.has(field.fieldtype)) return <textarea className="input" rows={field.fieldtype === "Small Text" ? 2 : 4} style={{ height: "auto", paddingTop: 9 }} value={value ?? ""} disabled={disabled} onChange={(event) => onChange(event.target.value)} />; const type = field.fieldtype === "Date" ? "date" : ["Int", "Float", "Currency", "Percent"].includes(field.fieldtype) ? "number" : "text"; return <input className="input" type={type} step={type === "number" ? "any" : undefined} value={value ?? ""} disabled={disabled} onChange={(event) => onChange(type === "number" ? (event.target.value === "" ? "" : Number(event.target.value)) : event.target.value)} />; }
function Field({ field, value, document, onChange, mode }) { const enabled = dependency(field, document); const locked = Boolean(field.read_only || (Boolean(field.set_only_once) && document.name)); const full = TEXT.has(field.fieldtype) || field.fieldtype === "Table"; if (field.fieldtype === "Table") return null; if (mode === "view") return <div style={full ? { gridColumn: "1 / -1" } : undefined}><p className="text-xs text-muted-foreground">{field.label || field.fieldname}</p><p className="text-sm font-medium">{shown(field, value)}</p>{Boolean(field.description) && <p className="text-xs text-muted-foreground" style={{ marginTop: 3 }}>{field.description}</p>}</div>; return <div className="field" style={full ? { gridColumn: "1 / -1" } : undefined}><label className="label">{field.label || field.fieldname}{Boolean(field.reqd) && <span style={{ color: "var(--danger)", marginLeft: 3 }}>*</span>}</label>{locked ? <div className="rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground">{shown(field, value)}</div> : <Control field={field} value={value} onChange={onChange} disabled={!enabled} document={document} />}{!enabled && <p className="text-xs text-muted-foreground">Complete the dependent field first.</p>}{Boolean(field.description) && <p className="text-xs text-muted-foreground">{field.description}</p>}</div>; }
function TableField({ field, schema, rows, onChange, mode, document }) { const columns = (schema?.fields || []).filter((item) => !item.hidden && !LAYOUT.has(item.fieldtype) && !SKIP.has(item.fieldtype)); const update = (index, key, value) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row)); return <div style={{ gridColumn: "1 / -1", overflowX: "auto" }}><div className="label" style={{ marginBottom: 8 }}>{field.label}</div><table className="tbl"><thead><tr>{columns.map((column) => <th key={column.fieldname}>{column.label || column.fieldname}</th>)}{mode !== "view" && <th />}</tr></thead><tbody>{(rows || []).map((row, index) => <tr key={index}>{columns.map((column) => <td key={column.fieldname} style={{ minWidth: 170 }}>{mode === "view" ? <span className="text-sm">{shown(column, row[column.fieldname])}</span> : <Control field={column} value={row[column.fieldname]} onChange={(value) => update(index, column.fieldname, value)} disabled={column.read_only} document={document} />}</td>)}{mode !== "view" && <td><button type="button" className="btn btn-ghost" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={15} /></button></td>}</tr>)}{!rows?.length && <tr><td colSpan={columns.length + 1} className="text-sm text-muted-foreground">No rows added.</td></tr>}</tbody></table>{mode !== "view" && <button type="button" className="btn btn-secondary" style={{ marginTop: 10 }} onClick={() => onChange([...(rows || []), {}])}><Plus size={15} /> Add Row</button>}</div>; }
function Section({ section, children }) { const [open, setOpen] = useState(!section.collapsible); return <div className="panel" style={{ marginBottom: 18, overflow: "visible" }}>{section.label && <button type="button" className="panel-head" onClick={() => section.collapsible && setOpen((old) => !old)} style={{ width: "100%", border: 0, background: "transparent", textAlign: "left", cursor: section.collapsible ? "pointer" : "default" }}><div className="panel-title" style={{ display: "flex", gap: 7, alignItems: "center" }}>{section.collapsible && (open ? <ChevronDown size={15} /> : <ChevronRight size={15} />)}{section.label}</div></button>}{open && children}</div>; }
export default function EmployeeMetadataLayout({ meta, value, onChange, mode = "edit" }) { const tabs = useMemo(() => tabsFor(meta?.fields), [meta]); const [active, setActive] = useState(""); const tab = tabs.find((item) => item.key === active) || tabs[0]; return <div><div style={{ display: "flex", gap: 4, padding: "0 20px", overflowX: "auto", borderBottom: "1px solid hsl(var(--border))", background: "var(--surface-2)" }}>{tabs.map((item) => <button key={item.key} type="button" onClick={() => setActive(item.key)} style={{ padding: "10px 16px", whiteSpace: "nowrap", border: 0, borderBottom: item.key === tab?.key ? "2px solid var(--brand)" : "2px solid transparent", background: item.key === tab?.key ? "var(--surface)" : "transparent", color: item.key === tab?.key ? "var(--brand)" : "var(--ink-3)", fontSize: 13, fontWeight: item.key === tab?.key ? 600 : 400 }}>{item.label}</button>)}</div><div style={{ padding: 20 }}>{sectionsFor(tab?.fields).map((section) => <Section key={section.key} section={section}><div style={{ padding: section.label ? "10px 20px 26px" : 20 }}><div style={{ display: "grid", gridTemplateColumns: `repeat(${Math.min(section.columns.length, 3)}, minmax(0, 1fr))`, gap: 20 }}>{section.columns.map((column, index) => <div key={index} style={{ display: "grid", gap: 14, alignContent: "start", minWidth: 0 }}>{column.map((field) => field.fieldtype === "Table" ? <TableField key={field.fieldname} field={field} schema={meta.child_tables?.[field.fieldname]} rows={value[field.fieldname] || []} onChange={(next) => onChange(field.fieldname, next)} mode={mode} document={value} /> : <Field key={field.fieldname} field={field} value={value[field.fieldname]} document={value} onChange={(next) => onChange(field.fieldname, next)} mode={mode} />)}</div>)}</div></div></Section>)}</div></div>; }
