import { callMethod } from "../frappeClient";
const NS="education_extension.staff_portal_api.buying.material_request_api";
export const getList=(params={})=>callMethod(`${NS}.get_list`,params);
export const getSingle=name=>callMethod(`${NS}.get_single`,{name});
export const create=data=>callMethod(`${NS}.create`,{data});
export const update=(name,data)=>callMethod(`${NS}.update`,{name,data});
export const remove=name=>callMethod(`${NS}.delete`,{name});
export const getConnections=name=>callMethod(`${NS}.get_connections`,{name});
export const submit=name=>callMethod(`${NS}.submit`,{name});
export const cancel=name=>callMethod(`${NS}.cancel`,{name});
export const getLookupOptions=(doctype,filters={})=>callMethod(`${NS}.get_lookup_options`,{doctype,filters});
export const getEmployeeDetails=employee=>callMethod(`${NS}.get_employee_details`,{employee});
export const getLinkedDetails=(linked_doctype,name,fields)=>callMethod(`${NS}.get_linked_details`,{linked_doctype,name,fields});
export const getDefaultCompany=()=>callMethod(`${NS}.get_default_company`);
export const getWarehouses=company=>callMethod(`${NS}.get_warehouses`,{company});
export const stop=name=>callMethod(`${NS}.stop_material_request`,{name});
export const unstop=name=>callMethod(`${NS}.unstop_material_request`,{name});
