import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import SearchableSelect from "@/components/shared/SearchableSelect";
import { getAppraisalTemplates, getSkills } from "@/services/hr/designationService";

export default function DesignationForm({ designation, onSave }) {
  const editing = Boolean(designation);
  const [form, setForm] = useState({ designation_name: "", description: "", appraisal_template: "", skills: [] });
  const [templates, setTemplates] = useState([]); const [skills, setSkills] = useState([]); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([getAppraisalTemplates(), getSkills()]).then(([templateRows, skillRows]) => { setTemplates(templateRows || []); setSkills(skillRows || []); }).catch(() => { setTemplates([]); setSkills([]); }); }, []);
  useEffect(() => { if (designation) setForm({ designation_name: designation.designation_name || designation.name || "", description: designation.description || "", appraisal_template: designation.appraisal_template || "", skills: (designation.skills || []).map((row) => ({ skill: row.skill || "" })) }); }, [designation]);
  const setField = (field, value) => setForm((old) => ({ ...old, [field]: value }));
  const setSkill = (index, value) => setForm((old) => ({ ...old, skills: old.skills.map((row, rowIndex) => rowIndex === index ? { skill: value } : row) }));
  async function submit(event) { event.preventDefault(); if (!form.designation_name.trim()) return toast.error("Designation is required"); if (form.skills.some((row) => !row.skill)) return toast.error("Select a skill or remove the empty row"); setSaving(true); try { await onSave(form); } finally { setSaving(false); } }
  return <form onSubmit={submit}><div className="panel-head"><div className="panel-title">Designation Information</div></div><div style={{ padding: "10px 20px 26px" }}><div className="grid-form"><div className="field"><label className="label">Designation <span style={{ color: "var(--danger)", marginLeft: 3 }}>*</span></label><input className="input" value={form.designation_name} onChange={(event) => setField("designation_name", event.target.value)} disabled={editing} />{editing && <p className="text-xs text-muted-foreground">The designation name cannot be changed after creation.</p>}</div><div className="field"><label className="label">Appraisal Template</label><SearchableSelect value={form.appraisal_template} onChange={(value) => setField("appraisal_template", value)} options={templates} label="Appraisal Template" placeholder="Search appraisal template..." /></div><div className="field" style={{ gridColumn: "1 / -1" }}><label className="label">Description</label><textarea className="input" rows={4} style={{ height: "auto", paddingTop: 9 }} value={form.description} onChange={(event) => setField("description", event.target.value)} /></div></div></div><div className="panel-head" style={{ borderTop: "1px solid hsl(var(--border))" }}><div className="panel-title">Required Skills</div></div><div style={{ padding: "10px 20px 26px" }}><div style={{ overflowX: "auto" }}><table className="tbl"><thead><tr><th>Skill</th><th style={{ width: 56 }} /></tr></thead><tbody>{form.skills.map((row, index) => <tr key={index}><td><SearchableSelect value={row.skill} onChange={(value) => setSkill(index, value)} options={skills} label="Skill" placeholder="Search skill..." /></td><td><button type="button" className="btn btn-ghost" aria-label="Remove skill" onClick={() => setForm((old) => ({ ...old, skills: old.skills.filter((_, rowIndex) => rowIndex !== index) }))}><Trash2 size={15} /></button></td></tr>)}{!form.skills.length && <tr><td colSpan={2} className="text-sm text-muted-foreground">No skills added.</td></tr>}</tbody></table></div><button type="button" className="btn btn-secondary" style={{ marginTop: 12 }} onClick={() => setForm((old) => ({ ...old, skills: [...old.skills, { skill: "" }] }))}><Plus size={15} /> Add Row</button></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 10, padding: "0 20px 20px" }}><button type="button" className="btn btn-secondary" onClick={() => window.history.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? "Saving..." : editing ? "Update Designation" : "Create Designation"}</button></div></form>;
}
