import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import SearchableSelect from "@/components/shared/SearchableSelect";
import { getErrorMessage } from "@/utils/errors";
import LeaveChildTable from "./LeaveChildTable";

const initialValue = field => field.type === "check" ? 0 : "";
const today = () => new Date().toISOString().slice(0,10);
const addMonths = (value, months) => {
  if (!value) return "";
  const [year, month, day] = value.split("-").map(Number);
  const targetMonth = month - 1 + months;
  const targetYear = year + Math.floor(targetMonth / 12);
  const normalizedMonth = ((targetMonth % 12) + 12) % 12;
  const lastDay = new Date(Date.UTC(targetYear, normalizedMonth + 1, 0)).getUTCDate();
  const date = new Date(Date.UTC(targetYear, normalizedMonth, Math.min(day, lastDay)));
  return date.toISOString().slice(0, 10);
};

function InputField({field,value,onChange,options,document,onRefreshOptions}) {
  const readOnly = typeof field.readOnly === "function" ? field.readOnly(document) : field.readOnly;
  if(readOnly) return <div className="rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground">{value===undefined||value===null||value===""?"—":String(value)}</div>;
  if(field.type==="link") return <SearchableSelect value={value||""} onChange={onChange} options={options[field.options]||[]} displayField={field.displayField} showId={field.showId} linkedDoctype={field.name==="employee"?null:field.linkedDoctype} label={field.label} placeholder={`Search ${field.label.toLowerCase()}...`} onRefreshOptions={onRefreshOptions} parentDefaults={{company:document.company||options.default_company||""}}/>;
  if(field.type==="select") return <select className="input" value={value||""} onChange={event=>onChange(event.target.value)}><option value="">Select {field.label}</option>{(field.values||[]).map(option=><option key={option} value={option}>{option}</option>)}</select>;
  if(field.type==="check") return <label className="flex h-9 items-center gap-2"><input type="checkbox" checked={!!Number(value)} onChange={event=>onChange(event.target.checked?1:0)}/><span className="text-sm">{Number(value)?"Yes":"No"}</span></label>;
  if(field.type==="textarea") return <textarea className="input" rows={4} value={value||""} onChange={event=>onChange(event.target.value)}/>;
  return <input className="input" type={field.type==="date"?"date":field.type==="number"?"number":"text"} step={field.type==="number"?"any":undefined} value={value??""} onChange={event=>onChange(event.target.value)}/>;
}

export default function LeaveDocumentForm({config,document,onSave}) {
  const [form,setForm]=useState({}); const [options,setOptions]=useState({}); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true);
  const visibleFields=useMemo(()=>config.fields.filter(field=>!field.show||field.show(form)),[config.fields,form]);
  useEffect(()=>{let active=true; config.service.options().then(value=>{if(active)setOptions(value||{});}).catch(error=>toast.error(getErrorMessage(error))).finally(()=>active&&setLoading(false)); return()=>{active=false};},[config]);
  async function refreshOptions(){try{const value=await config.service.options();setOptions(value||{});return value||{};}catch(error){toast.error(getErrorMessage(error));return null;}}
  useEffect(()=>{if(loading)return; const next=Object.fromEntries(config.fields.map(field=>[field.name,document?.[field.name]??initialValue(field)])); for(const table of config.tables||[]) next[table.name]=(document?.[table.name]||[]).map(row=>({...row})); if(!document){if(next.company!==undefined)next.company=options.default_company||""; if(next.is_active!==undefined)next.is_active=1; if(next.encashment_date!==undefined)next.encashment_date=today(); if(next.assignment_based_on!==undefined)next.assignment_based_on="Leave Period";} setForm(next);},[config,document,loading,options.default_company]);
  useEffect(()=>{if(config.key!=="leaveAllocation"||!form.employee||!form.leave_type)return; let active=true; config.service.balance(form.employee,form.leave_type,form.from_date||undefined).then(result=>active&&setForm(current=>({...current,current_balance:result?.balance??0}))).catch(()=>{}); return()=>{active=false};},[config,form.employee,form.leave_type,form.from_date]);
  useEffect(()=>{if(config.key!=="leaveEncashment"||!form.employee||!form.leave_period||!form.leave_type)return; let active=true; config.service.details({employee:form.employee,leave_period:form.leave_period,leave_type:form.leave_type,encashment_date:form.encashment_date||undefined}).then(result=>{if(!active)return; setForm(current=>({...current,leave_allocation:result.leave_allocation||"",leave_balance:result.leave_balance??0,actual_encashable_days:result.actual_encashable_days??0,encashment_days:result.encashment_days??result.actual_encashable_days??0,encashment_amount:result.encashment_amount??0,currency:result.currency||current.currency||"",company:result.company||current.company||""}));}).catch(error=>{if(active)toast.error(getErrorMessage(error));}); return()=>{active=false};},[config,form.employee,form.leave_period,form.leave_type,form.encashment_date]);
  useEffect(()=>{if(config.key!=="leavePolicyAssignment"||form.assignment_based_on!=="Leave Period"||!form.leave_period)return; const period=(options.leave_periods||[]).find(row=>row.name===form.leave_period); if(!period)return; setForm(current=>current.effective_from===period.from_date&&current.effective_to===period.to_date?current:{...current,effective_from:period.from_date||"",effective_to:period.to_date||""});},[config,form.assignment_based_on,form.leave_period,options.leave_periods]);
  function change(name,value,selectedOption){setForm(current=>{const next={...current,[name]:value}; if(name==="employee"){const employee=selectedOption?.name===value?selectedOption:(options.employees||[]).find(row=>row.name===value)||{}; next.employee_name=employee.employee_name||""; next.department=employee.department||""; next.company=employee.company||""; if(config.key==="leavePolicyAssignment"&&next.assignment_based_on==="Joining Date"){next.effective_from=employee.date_of_joining||""; next.effective_to=addMonths(employee.date_of_joining,12);}} if(config.key==="leaveAllocation"&&(name==="new_leaves_allocated"||name==="carry_forwarded_leaves")){next.total_leaves_allocated=Number(next.new_leaves_allocated||0)+Number(next.carry_forwarded_leaves||0);} if(config.key==="leavePolicyAssignment"){if(name==="leave_period"){const period=selectedOption?.name===value?selectedOption:(options.leave_periods||[]).find(row=>row.name===value)||{}; next.effective_from=period.from_date||""; next.effective_to=period.to_date||"";} if(name==="assignment_based_on"){if(value==="Leave Period"){const period=(options.leave_periods||[]).find(row=>row.name===next.leave_period)||{}; next.effective_from=period.from_date||""; next.effective_to=period.to_date||"";}else if(value==="Joining Date"){const employee=(options.employees||[]).find(row=>row.name===next.employee)||{}; next.leave_period=""; next.effective_from=employee.date_of_joining||""; next.effective_to=addMonths(employee.date_of_joining,12);}}} return next;});}
  async function weekly(){if(!form.from_date||!form.to_date||!form.weekly_off)return toast.error("From Date, To Date, and Weekly Off are required"); try{const result=await config.service.weekly(form);setForm(current=>({...current,holidays:result.holidays||[]}));toast.success("Weekly off dates added");}catch(error){toast.error(getErrorMessage(error));}}
  async function submit(event){event.preventDefault(); const required=visibleFields.find(field=>field.required&&(form[field.name]===undefined||form[field.name]===null||form[field.name]==="")); if(required)return toast.error(`${required.label} is required`); if(form.from_date&&form.to_date&&form.from_date>form.to_date)return toast.error("To Date cannot be before From Date"); if(config.key==="leaveEncashment"&&Number(form.encashment_days||0)<=0)return toast.error("There are no eligible leave days to encash"); if(config.key==="leaveEncashment"&&Number(form.encashment_days)>Number(form.actual_encashable_days||0))return toast.error(`Encashment Days cannot exceed Actual Encashable Days (${form.actual_encashable_days||0})`); const missingTable=(config.tables||[]).find(table=>table.required&&!(form[table.name]||[]).length); if(missingTable)return toast.error(`Add at least one row to ${missingTable.label}`); setSaving(true); try{await onSave(form);}finally{setSaving(false);}}
  if(loading)return <div className="p-5 text-sm text-muted-foreground">Loading form options…</div>;
  return <form onSubmit={submit}><div className="panel-head"><div className="panel-title">{config.singular} Information</div>{config.formAction==="weekly"&&<button type="button" className="btn btn-secondary" onClick={weekly}>Get Weekly Off Dates</button>}</div><div className="grid-form" style={{padding:"16px 20px 26px"}}>{visibleFields.map(field=><div className="field" key={field.name} style={field.full?{gridColumn:"1 / -1"}:undefined}><label className="label">{field.label}{field.required&&<span className="text-destructive"> *</span>}</label><InputField field={field} value={form[field.name]} onChange={(value,selectedOption)=>change(field.name,value,selectedOption)} options={options} document={form} onRefreshOptions={refreshOptions}/>{config.key==="leaveEncashment"&&field.name==="leave_type"&&!(options.leave_types||[]).length&&<p className="mt-1 text-xs text-amber-700">No Leave Type is enabled for encashment. <Link className="font-medium underline" to="/dashboard/leave-types">Enable Allow Encashment on a Leave Type</Link>.</p>}{config.key==="leaveEncashment"&&field.name==="encashment_days"&&<p className="mt-1 text-xs text-muted-foreground">Prefilled with Actual Encashable Days. You may enter a smaller number.</p>}</div>)}{(config.tables||[]).map(table=><LeaveChildTable key={table.name} table={table} rows={form[table.name]||[]} onChange={rows=>change(table.name,rows)} options={options}/>)}</div><div className="flex justify-end gap-2 p-5 pt-0"><button type="button" className="btn btn-secondary" onClick={()=>window.history.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?"Saving...":document?`Update ${config.singular}`:`Create ${config.singular}`}</button></div></form>;
}
