import { useEffect, useState } from "react";
import { FileText } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { PageHeader } from "@/components/shared/OriginalPrimitives";
import ConfirmDialog from "@/components/shared/ConfirmDialog";
import ConnectionsPanel from "@/pages/admin/hr/components/ConnectionsPanel";
import { getErrorMessage } from "@/utils/errors";

const show=value=>value===null||value===undefined||value===""?"—":typeof value==="number"?String(value):value;
export default function LeaveProfilePage({config}) {
  const{id}=useParams();const name=decodeURIComponent(id);const navigate=useNavigate();const[document,setDocument]=useState(null);const[connections,setConnections]=useState({});const[removeOpen,setRemoveOpen]=useState(false);
  async function load(){try{const[doc,linked]=await Promise.all([config.service.get(name),config.service.connections?.(name)||{}]);setDocument(doc);setConnections(linked||{});}catch(error){toast.error(getErrorMessage(error));}}
  useEffect(()=>{load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[name]);
  async function action(fn,message){try{const result=await fn(name);toast.success(message+(result?.granted!==undefined?`: ${result.granted} allocation(s) granted`:""));load();}catch(error){toast.error(getErrorMessage(error));}}
  async function remove(){try{await config.service.delete(name);toast.success(`${config.singular} deleted`);navigate(`/dashboard/${config.path}`);}catch(error){toast.error(getErrorMessage(error));}}
  if(!document)return <div className="text-sm text-muted-foreground">Loading {config.singular.toLowerCase()}…</div>;
  const actions=<div className="flex flex-wrap gap-2">{document.can_edit&&<button className="btn btn-secondary" onClick={()=>navigate(`/dashboard/${config.path}/${encodeURIComponent(name)}/edit`)}>Edit</button>}{config.profileAction==="grant"&&<button className="btn btn-primary" onClick={()=>action(config.service.grant,"Grant Leaves completed")}>Grant Leaves</button>}{config.submittable&&Number(document.docstatus)===0&&<button className="btn btn-primary" onClick={()=>action(config.service.submit,`${config.singular} submitted`)}>Submit</button>}{config.submittable&&Number(document.docstatus)===1&&<button className="btn btn-danger" onClick={()=>action(config.service.cancel,`${config.singular} cancelled`)}>Cancel</button>}{document.can_delete&&<button className="btn btn-danger" onClick={()=>setRemoveOpen(true)}>Delete</button>}</div>;
  return <><PageHeader eyebrow="HR · Leaves" title={document.title||document.leave_type_name||document.holiday_list_name||document.leave_block_list_name||document.employee_name||document.name} sub={document.name} button={actions}/><div className="panel"><div className="panel-head"><div className="panel-title">{config.singular} Information</div></div><div className="grid-form" style={{padding:"16px 20px 26px"}}>{config.fields.filter(field=>!field.virtual&&(!field.show||field.show(document))).map(field=><div key={field.name} style={field.full?{gridColumn:"1 / -1"}:undefined}><p className="text-xs text-muted-foreground">{field.label}</p><p className="whitespace-pre-wrap text-sm font-medium">{field.type==="check"?(Number(document[field.name])?"Yes":"No"):show(document[field.name])}</p></div>)}</div>{(config.tables||[]).map(table=><div key={table.name}><div className="panel-head border-t"><div className="panel-title">{table.label}</div></div><div className="overflow-x-auto p-5"><table className="tbl"><thead><tr>{table.fields.map(field=><th key={field.name}>{field.label}</th>)}</tr></thead><tbody>{(document[table.name]||[]).map((row,index)=><tr key={row.name||index}>{table.fields.map(field=><td key={field.name}>{field.type==="check"?(Number(row[field.name])?"Yes":"No"):show(row[field.name])}</td>)}</tr>)}{!(document[table.name]||[]).length&&<tr><td colSpan={table.fields.length} className="text-sm text-muted-foreground">No rows.</td></tr>}</tbody></table></div></div>)}</div><ConnectionsPanel groups={[{label:"HR",items:(config.connections||[]).map(connection=>({icon:FileText,label:connection.label,count:connections[connection.key],onClick:()=>navigate(`/dashboard/${connection.path}?${connection.query}=${encodeURIComponent(name)}`)}))}]}/><ConfirmDialog open={removeOpen} onClose={()=>setRemoveOpen(false)} onConfirm={remove} title={`Delete ${document.name}?`} description="This action cannot be undone." confirmLabel="Delete"/></>;
}
