import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import PageHeader from "@/components/shared/PageHeader";
import ReportTable from "@/components/shared/ReportTable";
import ReportToolbar from "@/components/shared/ReportToolbar";
import ReportPrintHeader from "@/components/shared/ReportPrintHeader";
import { getReportData } from "@/services/reportService";
import { callMethod } from "@/services/frappeClient";
import { getErrorMessage } from "@/utils/errors";
import { t } from "@/config/translations";
import { openReportPrintView } from "@/utils/reportPrintView";

const iso = (date) => date.toISOString().slice(0, 10);
const today = () => iso(new Date());
const monthAgo = () => { const date = new Date(); date.setMonth(date.getMonth() - 1); return iso(date); };
const yearAgo = () => { const date = new Date(); date.setMonth(date.getMonth() - 12); return iso(date); };
const yearStart = () => `${new Date().getFullYear()}-01-01`;
const yearEnd = () => `${new Date().getFullYear()}-12-31`;
const fiscalYear = () => String(new Date().getFullYear());
const field = (fieldname, label, fieldtype, extra = {}) => ({ fieldname, label, fieldtype, ...extra });
const normalizeColumn = (column, index) => {
  if (typeof column !== "string") return { ...column, label: t(column.label) };
  const [label, type = "Data", width] = column.split(":"); const [fieldtype, options] = type.split("/");
  return { label: t(label), fieldname: label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "") || `column_${index}`, fieldtype, options, width: Number(width) || undefined };
};

const statementFields = [
  field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("finance_book", "Finance Book", "Link", { options: "Finance Book" }),
  field("filter_based_on", "Filter Based On", "Select", { options: ["Fiscal Year", "Date Range"], default: "Fiscal Year", reqd: true }),
  field("period_start_date", "Start Date", "Date", { default: yearStart, requiredWhen: ["filter_based_on", "Date Range"], visibleWhen: ["filter_based_on", "Date Range"] }), field("period_end_date", "End Date", "Date", { default: yearEnd, requiredWhen: ["filter_based_on", "Date Range"], visibleWhen: ["filter_based_on", "Date Range"] }),
  field("from_fiscal_year", "Start Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true, visibleWhen: ["filter_based_on", "Fiscal Year"] }), field("to_fiscal_year", "End Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true, visibleWhen: ["filter_based_on", "Fiscal Year"] }),
  field("periodicity", "Periodicity", "Select", { options: ["Monthly", "Quarterly", "Half-Yearly", "Yearly"], default: "Yearly", reqd: true }), field("presentation_currency", "Currency", "Select", { dynamicOptions: "Currency" }),
  field("cost_center", "Cost Center", "MultiSelectList", { options: "Cost Center", companyFilter: true }), field("project", "Project", "MultiSelectList", { options: "Project", companyFilter: true }),
];

export const FINANCIAL_REPORTS = {
  "General Ledger": { slug: "general-ledger", fields: [
    field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("finance_book", "Finance Book", "Link", { options: "Finance Book" }), field("from_date", "From Date", "Date", { default: monthAgo, reqd: true }), field("to_date", "To Date", "Date", { default: today, reqd: true }),
    field("account", "Account", "MultiSelectList", { options: "Account", companyFilter: true }), field("voucher_no", "Voucher No", "Data"), field("against_voucher_no", "Against Voucher No", "Data"), field("party_type", "Party Type", "Select", { options: ["Customer", "Supplier", "Employee", "Shareholder"] }), field("party", "Party", "MultiSelectList", { dynamicLink: "party_type" }),
    field("categorize_by", "Categorize by", "Select", { options: ["Categorize by Voucher", "Categorize by Voucher (Consolidated)", "Categorize by Account", "Categorize by Party"], default: "Categorize by Voucher (Consolidated)" }), field("presentation_currency", "Currency", "Select", { dynamicOptions: "Currency" }), field("cost_center", "Cost Center", "MultiSelectList", { options: "Cost Center", companyFilter: true }), field("project", "Project", "MultiSelectList", { options: "Project", companyFilter: true }),
    field("include_dimensions", "Consider Accounting Dimensions", "Check", { default: 1 }), field("disable_opening_balance_calculation", "Disable Opening Balance Calculation", "Check"), field("show_opening_entries", "Show Opening Entries", "Check"), field("include_default_book_entries", "Include Default FB Entries", "Check", { default: 1 }), field("show_cancelled_entries", "Show Cancelled Entries", "Check"), field("show_net_values_in_party_account", "Show Net Values in Party Account", "Check"), field("show_amount_in_company_currency", "Show Credit / Debit in Company Currency", "Check"), field("add_values_in_transaction_currency", "Add Columns in Transaction Currency", "Check"), field("show_remarks", "Show Remarks", "Check"), field("ignore_err", "Ignore Exchange Rate Revaluation and Gain / Loss Journals", "Check"), field("ignore_cr_dr_notes", "Ignore System Generated Credit / Debit Notes", "Check"),
  ] },
  "Customer Ledger Summary": { slug: "customer-ledger-summary", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("from_date", "From Date", "Date", { default: monthAgo, reqd: true }), field("to_date", "To Date", "Date", { default: today, reqd: true }), field("finance_book", "Finance Book", "Link", { options: "Finance Book" }), field("party", "Customer", "Link", { options: "Customer" }), field("customer_group", "Customer Group", "Link", { options: "Customer Group" }), field("payment_terms_template", "Payment Terms Template", "Link", { options: "Payment Terms Template" }), field("territory", "Territory", "Link", { options: "Territory" }), field("sales_partner", "Sales Partner", "Link", { options: "Sales Partner" }), field("sales_person", "Sales Person", "Link", { options: "Sales Person" })] },
  "Supplier Ledger Summary": { slug: "supplier-ledger-summary", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true }), field("from_date", "From Date", "Date", { default: monthAgo, reqd: true }), field("to_date", "To Date", "Date", { default: today, reqd: true }), field("finance_book", "Finance Book", "Link", { options: "Finance Book" }), field("party", "Supplier", "Link", { options: "Supplier" }), field("supplier_group", "Supplier Group", "Link", { options: "Supplier Group" }), field("payment_terms_template", "Payment Terms Template", "Link", { options: "Payment Terms Template" })] },
  "Trial Balance": { slug: "trial-balance", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("fiscal_year", "Fiscal Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true }), field("from_date", "From Date", "Date", { default: yearStart }), field("to_date", "To Date", "Date", { default: yearEnd }), field("cost_center", "Cost Center", "MultiSelectList", { options: "Cost Center", companyFilter: true }), field("project", "Project", "MultiSelectList", { options: "Project", companyFilter: true }), field("finance_book", "Finance Book", "Link", { options: "Finance Book" }), field("presentation_currency", "Currency", "Select", { dynamicOptions: "Currency" }), field("with_period_closing_entry_for_opening", "With Period Closing Entry For Opening Balances", "Check", { default: 1 }), field("with_period_closing_entry_for_current_period", "Period Closing Entry For Current Period", "Check", { default: 1 }), field("show_zero_values", "Show zero values", "Check"), field("show_unclosed_fy_pl_balances", "Show unclosed fiscal year's P&L balances", "Check"), field("include_default_book_entries", "Include Default FB Entries", "Check", { default: 1 }), field("show_net_values", "Show net values in opening and closing columns", "Check", { default: 1 }), field("show_group_accounts", "Show Group Accounts", "Check", { default: 1 })] },
  "Profit and Loss Statement": { slug: "profit-and-loss", fields: [...statementFields, field("selected_view", "Select View", "Select", { options: ["Report", "Growth", "Margin"], default: "Report", reqd: true }), field("accumulated_values", "Accumulated Values", "Check"), field("include_default_book_entries", "Include Default FB Entries", "Check", { default: 1 }), field("show_zero_values", "Show zero values", "Check")] },
  "Balance Sheet": { slug: "balance-sheet", fields: [...statementFields, field("selected_view", "Select View", "Select", { options: ["Report", "Growth"], default: "Report", reqd: true }), field("accumulated_values", "Accumulated Values", "Check", { default: 1 }), field("include_default_book_entries", "Include Default FB Entries", "Check", { default: 1 }), field("show_zero_values", "Show zero values", "Check")] },
  "Cash Flow": { slug: "cash-flow", fields: [...statementFields.filter((f) => f.fieldname !== "presentation_currency"), field("include_default_book_entries", "Include Default FB Entries", "Check", { default: 1 }), field("show_opening_and_closing_balance", "Show Opening and Closing Balance", "Check")] },
  "Consolidated Financial Statement": { slug: "consolidated-financial-statement", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("filter_based_on", "Filter Based On", "Select", { options: ["Fiscal Year", "Date Range"], default: "Fiscal Year", reqd: true }), field("period_start_date", "Start Date", "Date", { default: yearStart, requiredWhen: ["filter_based_on", "Date Range"], visibleWhen: ["filter_based_on", "Date Range"] }), field("period_end_date", "End Date", "Date", { default: yearEnd, requiredWhen: ["filter_based_on", "Date Range"], visibleWhen: ["filter_based_on", "Date Range"] }), field("from_fiscal_year", "Start Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true, visibleWhen: ["filter_based_on", "Fiscal Year"] }), field("to_fiscal_year", "End Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true, visibleWhen: ["filter_based_on", "Fiscal Year"] }), field("finance_book", "Finance Book", "Link", { options: "Finance Book" }), field("report", "Report", "Select", { options: ["Profit and Loss Statement", "Balance Sheet", "Cash Flow"], default: "Balance Sheet", reqd: true }), field("presentation_currency", "Currency", "Select", { dynamicOptions: "Currency" }), field("accumulated_in_group_company", "Accumulated Values in Group Company", "Check"), field("include_default_book_entries", "Include Default FB Entries", "Check", { default: 1 }), field("show_zero_values", "Show zero values", "Check")] },
  "Gross Profit": { slug: "gross-profit", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("from_date", "From Date", "Date", { default: yearStart, reqd: true }), field("to_date", "To Date", "Date", { default: yearEnd, reqd: true }), field("sales_invoice", "Sales Invoice", "Link", { options: "Sales Invoice" }), field("group_by", "Group By", "Select", { options: ["Invoice", "Item Code", "Item Group", "Brand", "Warehouse", "Customer", "Customer Group", "Territory", "Sales Person", "Project", "Cost Center", "Monthly", "Payment Term"], default: "Invoice" }), field("item_group", "Item Group", "Link", { options: "Item Group" }), field("sales_person", "Sales Person", "Link", { options: "Sales Person" }), field("warehouse", "Warehouse", "Link", { options: "Warehouse", companyFilter: true }), field("cost_center", "Cost Center", "MultiSelectList", { options: "Cost Center", companyFilter: true }), field("project", "Project", "MultiSelectList", { options: "Project", companyFilter: true }), field("include_returned_invoices", "Include Returned Invoices (Stand-alone)", "Check", { default: 1 })] },
  "Profitability Analysis": { slug: "profitability-analysis", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("based_on", "Based On", "Select", { options: ["Cost Center", "Project", "Accounting Dimension"], default: "Cost Center", reqd: true }), field("accounting_dimension", "Accounting Dimension", "Link", { options: "Accounting Dimension", visibleWhen: ["based_on", "Accounting Dimension"], requiredWhen: ["based_on", "Accounting Dimension"] }), field("fiscal_year", "Fiscal Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true }), field("from_date", "From Date", "Date", { default: yearStart }), field("to_date", "To Date", "Date", { default: yearEnd }), field("show_zero_values", "Show zero values", "Check")] },
  "Sales Invoice Trends": { slug: "sales-invoice-trends", fields: [field("period", "Period", "Select", { options: ["Monthly", "Quarterly", "Half-Yearly", "Yearly"], default: "Monthly" }), field("based_on", "Based On", "Select", { options: ["Item", "Item Group", "Customer", "Customer Group", "Territory", "Project"], default: "Item" }), field("group_by", "Group By", "Select", { options: ["Item", "Customer"] }), field("fiscal_year", "Fiscal Year", "Link", { options: "Fiscal Year", default: fiscalYear }), field("company", "Company", "Link", { options: "Company", defaultFirst: true })] },
  "Purchase Invoice Trends": { slug: "purchase-invoice-trends", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("period", "Period", "Select", { options: ["Monthly", "Quarterly", "Half-Yearly", "Yearly"], default: "Monthly" }), field("fiscal_year", "Fiscal Year", "Link", { options: "Fiscal Year", default: fiscalYear }), field("period_based_on", "Period based On", "Select", { options: [{ value: "posting_date", label: "Posting Date" }, { value: "bill_date", label: "Billing Date" }], default: "posting_date" }), field("based_on", "Based On", "Select", { options: ["Item", "Item Group", "Supplier", "Supplier Group", "Project"], default: "Item" }), field("group_by", "Group By", "Select", { options: ["Item", "Supplier"] })] },
  "Trial Balance for Party": { slug: "trial-balance-for-party", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("fiscal_year", "Fiscal Year", "Link", { options: "Fiscal Year", default: fiscalYear, reqd: true }), field("from_date", "From Date", "Date", { default: yearStart }), field("to_date", "To Date", "Date", { default: yearEnd }), field("party_type", "Party Type", "Link", { options: "Party Type", default: "Customer", reqd: true }), field("party", "Party", "Link", { dynamicLink: "party_type" }), field("account", "Account", "MultiSelectList", { options: "Account", companyFilter: true }), field("show_zero_values", "Show zero values", "Check"), field("exclude_zero_balance_parties", "Exclude Zero Balance Parties", "Check", { default: 1 })] },
  "Payment Period Based On Invoice Date": { slug: "payment-period-based-on-invoice-date", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("from_date", "From Date", "Date", { default: yearStart }), field("to_date", "To Date", "Date", { default: today }), field("payment_type", "Payment Type", "Select", { options: ["Incoming", "Outgoing"], default: "Incoming" }), field("party_type", "Party Type", "Select", { options: ["Customer", "Supplier"] }), field("party", "Party", "Link", { dynamicLink: "party_type" })] },
  "Sales Partners Commission": { slug: "sales-partners-commission", fields: [] },
  "Customer Credit Balance": { slug: "customer-credit-balance", fields: [field("company", "Company", "Link", { options: "Company", defaultFirst: true, reqd: true }), field("customer", "Customer", "Link", { options: "Customer" })] },
  "Sales Payment Summary": { slug: "sales-payment-summary", fields: [field("from_date", "From Date", "Date", { default: today, reqd: true }), field("to_date", "To Date", "Date", { default: today, reqd: true }), field("company", "Company", "Link", { options: "Company", defaultFirst: true }), field("owner", "Owner", "Link", { options: "User" }), field("is_pos", "Show only POS", "Check"), field("payment_detail", "Show Payment Details", "Check")] },
  "Address And Contacts": { slug: "address-and-contacts", fields: [field("party_type", "Party Type", "Select", { options: ["Customer", "Supplier", "Sales Partner", "Lead"], reqd: true }), field("party_name", "Party Name", "Link", { dynamicLink: "party_type" })] },
  "Unpaid Expense Claim": { slug: "unpaid-expense-claim", fields: [field("employee", "Employee", "Link", { options: "Employee" })] },
  "Vehicle Expenses": { slug: "vehicle-expenses", fields: [field("filter_based_on", "Filter Based On", "Select", { options: ["Fiscal Year", "Date Range"], default: "Fiscal Year", reqd: true }), field("fiscal_year", "Fiscal Year", "Link", { options: "Fiscal Year", default: fiscalYear, requiredWhen: ["filter_based_on", "Fiscal Year"], visibleWhen: ["filter_based_on", "Fiscal Year"] }), field("from_date", "From Date", "Date", { default: yearAgo, requiredWhen: ["filter_based_on", "Date Range"], visibleWhen: ["filter_based_on", "Date Range"] }), field("to_date", "To Date", "Date", { default: today, requiredWhen: ["filter_based_on", "Date Range"], visibleWhen: ["filter_based_on", "Date Range"] }), field("vehicle", "Vehicle", "Link", { options: "Vehicle" }), field("employee", "Employee", "Link", { options: "Employee" })] },
};

function Filter({ config, value, values, onChange }) {
  const [options, setOptions] = useState([]); const doctype = config.dynamicLink ? values[config.dynamicLink] : config.dynamicOptions || config.options; const listType = (["Link", "MultiSelectList"].includes(config.fieldtype) || Boolean(config.dynamicOptions)) && typeof doctype === "string";
  useEffect(() => { if (!listType || !doctype || Array.isArray(doctype)) { setOptions([]); return; } const filters = config.companyFilter && values.company ? { company: values.company } : undefined; callMethod("frappe.client.get_list", { doctype, fields: ["name"], ...(filters ? { filters } : {}), limit_page_length: 500, order_by: "name asc" }).then((rows) => { const next = (rows || []).map((row) => row.name); setOptions(next); if (config.defaultFirst && !value && next[0]) onChange(next[0]); }).catch(() => setOptions([])); }, [config, doctype, listType, value, values.company]);
  const required = config.reqd || (config.requiredWhen && values[config.requiredWhen[0]] === config.requiredWhen[1]); if (config.visibleWhen && values[config.visibleWhen[0]] !== config.visibleWhen[1]) return null; const selectValue = Array.isArray(value) ? value[0] || "" : value || "";
  if (config.fieldtype === "Check") return <div className="flex min-h-16 items-end"><label className="flex h-9 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={Boolean(value)} onChange={(e) => onChange(e.target.checked ? 1 : 0)} />{config.label}</label></div>;
  return <div className="space-y-2"><Label className="font-semibold">{config.label}{required ? <span className="text-destructive"> *</span> : null}</Label>{["Date", "Data"].includes(config.fieldtype) ? <Input className="w-56" type={config.fieldtype === "Date" ? "date" : "text"} value={value || ""} onChange={(e) => onChange(e.target.value)} /> : <Select value={selectValue} onValueChange={(next) => onChange(config.fieldtype === "MultiSelectList" ? [next] : next)}><SelectTrigger className="w-56"><SelectValue placeholder={`Select ${config.label.toLowerCase()}`} /></SelectTrigger><SelectContent>{(listType ? options : config.options || []).map((option) => { const item = typeof option === "object" ? option.value : option; const label = typeof option === "object" ? option.label : option; return <SelectItem key={item} value={item}>{label}</SelectItem>; })}</SelectContent></Select>}</div>;
}

export default function FinancialReportPage({ reportName }) {
  const config = FINANCIAL_REPORTS[reportName]; const [searchParams] = useSearchParams(); const queryKey = searchParams.toString(); const defaults = useMemo(() => Object.fromEntries(config.fields.map((f) => { const queryValue = searchParams.get(f.fieldname); if (queryValue !== null) { if (f.fieldtype === "Check") return [f.fieldname, ["1", "true", "yes"].includes(queryValue.toLowerCase()) ? 1 : 0]; if (f.fieldtype === "MultiSelectList") return [f.fieldname, queryValue ? queryValue.split(",").filter(Boolean) : []]; return [f.fieldname, queryValue]; } return [f.fieldname, typeof f.default === "function" ? f.default() : f.default ?? (f.fieldtype === "Check" ? 0 : f.fieldtype === "MultiSelectList" ? [] : "")]; })), [config, queryKey]);
  const [values, setValues] = useState(defaults); const [columns, setColumns] = useState([]); const [rows, setRows] = useState([]); const [visibleRows, setVisibleRows] = useState([]); const [loading, setLoading] = useState(false); const [hasRun, setHasRun] = useState(false);
  const setFilter = (fieldname) => (value) => setValues((current) => ({ ...current, [fieldname]: value, ...(fieldname === "company" ? { account: [], cost_center: [], project: [] } : {}), ...(fieldname === "party_type" ? { party: [], party_name: "" } : {}) }));
  async function load() { const missing = config.fields.find((f) => (f.reqd || (f.requiredWhen && values[f.requiredWhen[0]] === f.requiredWhen[1])) && (!f.visibleWhen || values[f.visibleWhen[0]] === f.visibleWhen[1]) && (!values[f.fieldname] || (Array.isArray(values[f.fieldname]) && !values[f.fieldname].length))); if (missing) { toast.error(`${missing.label} is required.`); return; } try { setLoading(true); const filters = Object.fromEntries(Object.entries(values).filter(([, value]) => value !== "" && value !== undefined && (!Array.isArray(value) || value.length))); const result = await getReportData(reportName, filters); const nextColumns = (result.columns || []).map(normalizeColumn); const normalizedRows = (result.result || []).map((row) => Array.isArray(row) ? Object.fromEntries(nextColumns.map((column, index) => [column.fieldname, row[index]])) : row); setColumns(nextColumns); setRows(normalizedRows.filter((row) => !Array.isArray(row))); setHasRun(true); } catch (error) { toast.error(getErrorMessage(error)); } finally { setLoading(false); } }
  const printFilters = config.fields.map((f) => ({ label: f.label, value: Array.isArray(values[f.fieldname]) ? values[f.fieldname].join(", ") : values[f.fieldname] })).filter((f) => f.value !== "" && f.value !== 0); const print = () => openReportPrintView({ title: reportName, filters: printFilters, columns, rows: visibleRows });
  return <><PageHeader title={reportName} description={hasRun ? `${rows.length} row${rows.length === 1 ? "" : "s"}` : "Select filters and run the report"}><ReportToolbar filenameBase={config.slug} columns={columns} rows={visibleRows} onPrint={print} /></PageHeader><Card className="no-print mb-4 p-4"><div className="grid grid-cols-1 items-end gap-4 sm:grid-cols-2 lg:grid-cols-4">{config.fields.map((filter) => <Filter key={filter.fieldname} config={filter} value={values[filter.fieldname]} values={values} onChange={setFilter(filter.fieldname)} />)}<Button onClick={load} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Run Report</Button></div></Card>{hasRun ? <div className="report-printable rounded-md border"><ReportPrintHeader title={reportName} filters={printFilters} /><ReportTable columns={columns} rows={rows} onVisibleRowsChange={setVisibleRows} emptyMessage={`No ${reportName.toLowerCase()} data found`} /></div> : <Card className="p-8 text-center text-sm text-muted-foreground">Select filters and run the report.</Card>}</>;
}
