import * as materialRequest from "@/services/buying/materialRequestService";
import * as purchaseOrder from "@/services/buying/purchaseOrderService";
import * as requestForQuotation from "@/services/buying/requestForQuotationService";
import * as supplierQuotation from "@/services/buying/supplierQuotationService";
import * as item from "@/services/buying/itemService";
import * as itemPrice from "@/services/buying/itemPriceService";
import * as priceList from "@/services/buying/priceListService";
import * as itemGroup from "@/services/buying/itemGroupService";
import * as productBundle from "@/services/buying/productBundleService";
import * as supplierGroup from "@/services/buying/supplierGroupService";
import * as pricingRule from "@/services/buying/pricingRuleService";
import * as promotionalScheme from "@/services/buying/promotionalSchemeService";
import * as purchaseTaxesTemplate from "@/services/buying/purchaseTaxesTemplateService";
import * as termsAndConditions from "@/services/buying/termsAndConditionsService";

const f=(name,label,type="text",extra={})=>({name,label,type,...extra});
const itemLink=(extra={})=>f("item_code","Item","link",{doctype:"Item",displayField:"item_name",showId:true,required:true,...extra});
const supplier=(extra={})=>f("supplier","Supplier","link",{doctype:"Supplier",displayField:"supplier_name",showId:true,required:true,...extra});
const company=()=>f("company","Company","link",{doctype:"Company",required:true});
const itemFields=[itemLink({fetch:{item_name:"item_name",stock_uom:"stock_uom",uom:"stock_uom"}}),f("item_name","Item Name","text",{readOnly:true}),f("description","Description","textarea"),f("qty","Quantity","number",{required:true}),f("uom","UOM","link",{doctype:"UOM",required:true}),f("stock_uom","Stock UOM","text",{readOnly:true}),f("conversion_factor","Conversion Factor","number",{default:1}),f("schedule_date","Schedule Date","date"),f("warehouse","Warehouse","link",{doctype:"Warehouse"}),f("rate","Rate","currency"),f("amount","Amount","currency",{readOnly:true})];
const transaction=(title,plural,base,service,fields,tables,statuses=[])=>({eyebrow:"Buying",title,plural,base,service,defaultCompany:true,submittable:true,titleField:"name",statusField:"status",statuses,statusColors:{Draft:"neutral",Submitted:"info",Stopped:"warning",Cancelled:"danger",Completed:"success",Closed:"neutral",Expired:"danger","To Receive and Bill":"warning","To Bill":"info","To Receive":"warning"},list:["name",...fields.filter(x=>["supplier_name","company","transaction_date","schedule_date","valid_till","grand_total","status"].includes(x.name)).map(x=>x.name),"docstatus"],fields,tables});
export const CONFIG={
"material-request":Object.assign(transaction("Material Request","Material Requests","material-requests",materialRequest,[f("naming_series","Series","select",{required:true,default:"MAT-MR-.YYYY.-",options:["MAT-MR-.YYYY.-"]}),f("material_request_type","Request Type","select",{required:true,default:"Purchase",options:["Purchase","Material Transfer","Material Issue","Manufacture","Customer Provided"]}),f("transaction_date","Transaction Date","date",{required:true,default:"today",postingLock:true}),f("schedule_date","Required By","date"),company(),f("set_warehouse","Default Target Warehouse","link",{doctype:"Warehouse"}),f("set_from_warehouse","Default Source Warehouse","link",{doctype:"Warehouse"}),f("purpose","Purpose","textarea",{full:true})],[{name:"items",label:"Items",summary:["item_code","qty","uom","schedule_date","warehouse"],fields:itemFields}],["Draft","Submitted","Stopped","Cancelled","Pending","Partially Ordered","Ordered","Transferred","Issued"]),{connectionItems:[{key:"purchase_orders",label:"Purchase Orders",path:"/dashboard/purchase-orders",filter:"material_request"},{key:"supplier_quotations",label:"Supplier Quotations",path:"/dashboard/supplier-quotations",filter:"material_request"}]}),
"purchase-order":Object.assign(transaction("Purchase Order","Purchase Orders","purchase-orders",purchaseOrder,[f("naming_series","Series","select",{required:true,default:"PUR-ORD-.YYYY.-",options:["PUR-ORD-.YYYY.-"]}),supplier({fetch:{supplier_name:"supplier_name",default_currency:"currency",default_price_list:"buying_price_list"}}),f("supplier_name","Supplier Name","text",{readOnly:true}),company(),f("transaction_date","Order Date","date",{required:true,default:"today",postingLock:true}),f("schedule_date","Required By","date"),f("currency","Currency","link",{doctype:"Currency",required:true}),f("conversion_rate","Exchange Rate","number",{required:true,default:1}),f("buying_price_list","Price List","link",{doctype:"Price List",section:"Currency and Price List",collapsible:true}),f("taxes_and_charges","Taxes Template","link",{doctype:"Purchase Taxes and Charges Template",section:"Taxes and Charges",collapsible:true}),f("additional_discount_percentage","Additional Discount %","number",{section:"Totals",collapsible:true}),f("discount_amount","Discount Amount","currency",{section:"Totals"}),f("net_total","Net Total","currency",{readOnly:true,section:"Totals"}),f("grand_total","Grand Total","currency",{readOnly:true,section:"Totals"}),f("tc_name","Terms and Conditions","link",{doctype:"Terms and Conditions",section:"Terms",collapsible:true}),f("terms","Terms","textarea",{section:"Terms",full:true}),f("status","Status","select",{default:"Draft",options:["Draft","On Hold","To Receive and Bill","To Bill","To Receive","Completed","Cancelled","Closed","Delivered"]})],[{name:"items",label:"Items",summary:["item_code","qty","uom","rate","amount"],fields:itemFields},{name:"taxes",label:"Taxes",summary:["charge_type","account_head","rate","tax_amount"],fields:[f("charge_type","Charge Type","select",{options:["Actual","On Net Total","On Previous Row Amount","On Previous Row Total","On Item Quantity"]}),f("account_head","Account Head","link",{doctype:"Account"}),f("description","Description"),f("rate","Rate","number"),f("tax_amount","Tax Amount","currency")]}],["Draft","On Hold","To Receive and Bill","To Bill","To Receive","Completed","Cancelled","Closed","Delivered"]),{connectionItems:[{key:"purchase_invoices",label:"Purchase Invoices",path:"/dashboard/purchase-invoices",filter:"purchase_order"},{key:"material_requests",label:"Material Requests",path:"/dashboard/material-requests",filter:"purchase_order"}]}),
"request-for-quotation":transaction("Request for Quotation","Requests for Quotation","request-for-quotation",requestForQuotation,[f("naming_series","Series","select",{required:true,default:"PUR-RFQ-.YYYY.-",options:["PUR-RFQ-.YYYY.-"]}),company(),f("transaction_date","Date","date",{required:true,default:"today",postingLock:true}),f("schedule_date","Required By","date"),f("subject","Subject","text",{required:true}),f("message_for_supplier","Message for Supplier","textarea",{full:true}),f("status","Status","select",{default:"Draft",options:["Draft","Submitted","Cancelled"]})],[{name:"items",label:"Items",summary:["item_code","qty","uom","schedule_date"],fields:itemFields},{name:"suppliers",label:"Suppliers",summary:["supplier","supplier_name","contact","email_id","send_email"],fields:[supplier({fetch:{supplier_name:"supplier_name"}}),f("supplier_name","Supplier Name","text",{readOnly:true}),f("contact","Contact","link",{doctype:"Contact"}),f("email_id","Email","email"),f("send_email","Send Email","check")]}],["Draft","Submitted","Cancelled"]),
"supplier-quotation":transaction("Supplier Quotation","Supplier Quotations","supplier-quotations",supplierQuotation,[f("naming_series","Series","select",{required:true,default:"PUR-SQTN-.YYYY.-",options:["PUR-SQTN-.YYYY.-"]}),supplier({fetch:{supplier_name:"supplier_name",default_currency:"currency"}}),f("supplier_name","Supplier Name","text",{readOnly:true}),company(),f("transaction_date","Date","date",{required:true,default:"today",postingLock:true}),f("valid_till","Valid Till","date"),f("currency","Currency","link",{doctype:"Currency",required:true}),f("conversion_rate","Exchange Rate","number",{required:true,default:1}),f("net_total","Net Total","currency",{readOnly:true,section:"Totals",collapsible:true}),f("grand_total","Grand Total","currency",{readOnly:true,section:"Totals"}),f("status","Status","select",{default:"Draft",options:["Draft","Submitted","Stopped","Cancelled","Expired"]})],[{name:"items",label:"Items",summary:["item_code","qty","uom","rate","amount"],fields:itemFields}],["Draft","Submitted","Stopped","Cancelled","Expired"]),
"item":{connectionItems:[{key:"item_prices",label:"Item Prices",path:"/dashboard/item-prices",filter:"item_code"},{key:"purchase_order_items",label:"Purchase Order Items",path:"/dashboard/purchase-orders",filter:"item_code"},{key:"material_request_items",label:"Material Request Items",path:"/dashboard/material-requests",filter:"item_code"}],eyebrow:"Buying",title:"Item",plural:"Items",base:"items",service:item,titleField:"item_name",list:["name","item_name","item_group","stock_uom","standard_rate","is_stock_item","disabled"],fields:[f("item_code","Item Code","text",{required:true,immutable:true}),f("item_name","Item Name","text",{required:true}),f("item_group","Item Group","link",{doctype:"Item Group",required:true}),f("description","Description","textarea",{full:true}),f("stock_uom","Stock UOM","link",{doctype:"UOM",required:true}),f("is_stock_item","Maintain Stock","check",{default:1}),f("standard_rate","Standard Selling Rate","currency"),f("valuation_rate","Valuation Rate","currency"),f("disabled","Disabled","check"),f("is_sales_item","Allow Sales","check",{default:1}),f("is_purchase_item","Allow Purchase","check",{default:1}),f("has_variants","Has Variants","check"),f("variant_of","Variant Of","link",{doctype:"Item",displayField:"item_name",showId:true}),f("image","Image","image")]},
"item-price":{eyebrow:"Buying",title:"Item Price",plural:"Item Prices",base:"item-prices",service:itemPrice,titleField:"item_name",list:["name","item_code","item_name","price_list","price_list_rate","currency","uom"],fields:[itemLink({fetch:{item_name:"item_name",stock_uom:"uom"}}),f("item_name","Item Name","text",{readOnly:true}),f("price_list","Price List","link",{doctype:"Price List",required:true}),f("uom","UOM","link",{doctype:"UOM",required:true}),f("price_list_rate","Rate","currency",{required:true}),f("currency","Currency","link",{doctype:"Currency"}),f("valid_from","Valid From","date"),f("valid_upto","Valid Upto","date")]},
"price-list":{eyebrow:"Buying",title:"Price List",plural:"Price Lists",base:"price-lists",service:priceList,titleField:"name",list:["name","currency","buying","selling","enabled"],fields:[f("price_list_name","Price List Name","text",{required:true,immutable:true}),f("currency","Currency","link",{doctype:"Currency",required:true}),f("buying","Buying","check",{default:1}),f("selling","Selling","check"),f("enabled","Enabled","check",{default:1})]},
"item-group":{eyebrow:"Buying",title:"Item Group",plural:"Item Groups",base:"item-groups",service:itemGroup,titleField:"name",list:["name","parent_item_group","is_group"],fields:[f("item_group_name","Item Group Name","text",{required:true,immutable:true}),f("parent_item_group","Parent Item Group","link",{doctype:"Item Group"}),f("is_group","Is Group","check"),f("image","Image","image")]},
"product-bundle":{eyebrow:"Buying",title:"Product Bundle",plural:"Product Bundles",base:"product-bundles",service:productBundle,titleField:"new_item_code",list:["name","new_item_code","description","disabled"],fields:[f("new_item_code","Parent Item","link",{doctype:"Item",displayField:"item_name",showId:true,required:true}),f("description","Description","textarea",{full:true}),f("disabled","Disabled","check")],tables:[{name:"items",label:"Bundle Items",summary:["item_code","qty","uom"],fields:[itemLink(),f("qty","Quantity","number",{required:true}),f("uom","UOM","link",{doctype:"UOM"}),f("description","Description","textarea")]}]},
"supplier-group":{connectionItems:[{key:"suppliers",label:"Suppliers",path:"/dashboard/suppliers",filter:"supplier_group"}],eyebrow:"Buying",title:"Supplier Group",plural:"Supplier Groups",base:"supplier-groups",service:supplierGroup,titleField:"name",list:["name","parent_supplier_group","is_group"],fields:[f("supplier_group_name","Supplier Group Name","text",{required:true,immutable:true}),f("parent_supplier_group","Parent Supplier Group","link",{doctype:"Supplier Group"}),f("is_group","Is Group","check"),f("payment_terms","Payment Terms","link",{doctype:"Payment Terms Template"})]},
"pricing-rule":{eyebrow:"Buying",defaultCompany:true,title:"Pricing Rule",plural:"Pricing Rules",base:"pricing-rules",service:pricingRule,titleField:"title",list:["name","title","apply_on","price_or_product_discount","company","valid_from","valid_upto","disable"],clearConditionalTablesOn:"apply_on",fields:[f("naming_series","Series","select",{default:"PRLE-.####",options:["PRLE-.####"]}),f("title","Title","text",{required:true}),f("apply_on","Apply On","select",{required:true,default:"Item Code",options:["Item Code","Item Group","Brand","Transaction"]}),f("price_or_product_discount","Discount Type","select",{required:true,options:["Price","Product"]}),company(),f("currency","Currency","link",{doctype:"Currency",required:true}),f("buying","Buying","check",{default:1}),f("selling","Selling","check"),f("valid_from","Valid From","date"),f("valid_upto","Valid Upto","date"),f("min_qty","Minimum Quantity","number"),f("max_qty","Maximum Quantity","number"),f("rate_or_discount","Rate or Discount","select",{options:["Rate","Discount Percentage","Discount Amount"]}),f("rate","Rate","currency"),f("discount_percentage","Discount Percentage","number"),f("discount_amount","Discount Amount","currency"),f("disable","Disabled","check")],tables:[{name:"items",label:"Items",summary:["item_code","uom"],showWhen:{field:"apply_on",value:"Item Code"},requiredWhen:{field:"apply_on",value:"Item Code"},fields:[f("item_code","Item Code","link",{doctype:"Item",displayField:"item_name",showId:true,required:true}),f("uom","UOM","link",{doctype:"UOM"})]},{name:"item_groups",label:"Item Groups",summary:["item_group","uom"],showWhen:{field:"apply_on",value:"Item Group"},requiredWhen:{field:"apply_on",value:"Item Group"},fields:[f("item_group","Item Group","link",{doctype:"Item Group",required:true}),f("uom","UOM","link",{doctype:"UOM"})]},{name:"brands",label:"Brands",summary:["brand","uom"],showWhen:{field:"apply_on",value:"Brand"},requiredWhen:{field:"apply_on",value:"Brand"},fields:[f("brand","Brand","link",{doctype:"Brand",required:true}),f("uom","UOM","link",{doctype:"UOM"})]}]},
"promotional-scheme":{eyebrow:"Buying",defaultCompany:true,title:"Promotional Scheme",plural:"Promotional Schemes",base:"promotional-schemes",service:promotionalScheme,titleField:"name",list:["name","apply_on","company","valid_from","valid_upto","disable"],fields:[f("name","Scheme Name","text",{required:true,immutable:true}),f("apply_on","Apply On","select",{required:true,options:["Item Code","Item Group","Brand","Transaction"]}),company(),f("currency","Currency","link",{doctype:"Currency"}),f("buying","Buying","check",{default:1}),f("selling","Selling","check"),f("valid_from","Valid From","date"),f("valid_upto","Valid Upto","date"),f("disable","Disabled","check")]},
"purchase-taxes-template":{eyebrow:"Buying",defaultCompany:true,title:"Purchase Taxes and Charges Template",plural:"Purchase Taxes and Charges Templates",base:"purchase-taxes-templates",service:purchaseTaxesTemplate,titleField:"title",list:["name","title","company","is_default","disabled"],fields:[f("title","Title","text",{required:true}),company(),f("is_default","Default","check"),f("disabled","Disabled","check"),f("tax_category","Tax Category","link",{doctype:"Tax Category"})],tables:[{name:"taxes",label:"Taxes",summary:["charge_type","account_head","rate","tax_amount"],fields:[f("charge_type","Charge Type","select",{options:["Actual","On Net Total","On Previous Row Amount","On Previous Row Total","On Item Quantity"]}),f("account_head","Account Head","link",{doctype:"Account"}),f("description","Description"),f("rate","Rate","number"),f("tax_amount","Tax Amount","currency")]}]},
"terms-and-conditions":{eyebrow:"Buying",title:"Terms and Conditions",plural:"Terms and Conditions",base:"terms-and-conditions",service:termsAndConditions,titleField:"title",list:["name","buying","selling","disabled"],fields:[f("title","Title","text",{required:true,immutable:true}),f("buying","Buying","check",{default:1}),f("selling","Selling","check"),f("disabled","Disabled","check"),f("terms","Terms","textarea",{required:true,full:true})]}
};

const mappedItems=(doc,extra=()=>({}))=>(doc.items||[]).map(row=>({
  item_code:row.item_code,item_name:row.item_name,description:row.description,
  qty:row.qty,uom:row.uom,stock_uom:row.stock_uom,conversion_factor:row.conversion_factor||1,
  schedule_date:row.schedule_date,warehouse:row.warehouse,rate:row.rate,...extra(row),
}));

CONFIG["material-request"].getStatusActions=doc=>doc.docstatus===1?[{
  label:doc.status==="Stopped"?"Unstop":"Stop",
  run:doc.status==="Stopped"?materialRequest.unstop:materialRequest.stop,
  success:doc.status==="Stopped"?"Material Request reopened":"Material Request stopped",
}]:[];
CONFIG["material-request"].getCreateActions=doc=>doc.docstatus===1&&doc.status!=="Stopped"?[
  {label:"Purchase Order",path:"/dashboard/purchase-orders/new",prefill:source=>({material_request:source.name,company:source.company,schedule_date:source.schedule_date,items:mappedItems(source,row=>({material_request:source.name,material_request_item:row.name}))})},
  {label:"Request for Quotation",path:"/dashboard/request-for-quotation/new",prefill:source=>({material_request:source.name,company:source.company,schedule_date:source.schedule_date,items:mappedItems(source,row=>({material_request:source.name,material_request_item:row.name}))})},
  {label:"Supplier Quotation",path:"/dashboard/supplier-quotations/new",prefill:source=>({material_request:source.name,company:source.company,schedule_date:source.schedule_date,items:mappedItems(source,row=>({material_request:source.name,material_request_item:row.name}))})},
]:[];

CONFIG["purchase-order"].getStatusActions=doc=>{
  if(doc.docstatus!==1)return[];
  if(["Closed","Delivered"].includes(doc.status))return[{label:"Re-open",run:name=>purchaseOrder.setStatus(name,"Submitted"),success:"Purchase Order reopened"}];
  if(Number(doc.per_received||0)<100||Number(doc.per_billed||0)<100)return[{label:"Close",run:name=>purchaseOrder.setStatus(name,"Closed"),success:"Purchase Order closed"}];
  return[];
};
CONFIG["purchase-order"].getCreateActions=doc=>doc.docstatus===1&&doc.status!=="Closed"?[
  {label:"Purchase Invoice",path:"/dashboard/purchase-invoices/new",prefill:source=>({purchase_order:source.name,supplier:source.supplier,supplier_name:source.supplier_name,company:source.company,currency:source.currency,items:mappedItems(source,row=>({purchase_order:source.name,po_detail:row.name}))})},
  {label:"Purchase Receipt",path:"/dashboard/purchase-receipts/new",prefill:source=>({purchase_order:source.name,supplier:source.supplier,supplier_name:source.supplier_name,company:source.company,currency:source.currency,items:mappedItems(source,row=>({purchase_order:source.name,purchase_order_item:row.name}))})},
]:[];

CONFIG["supplier-quotation"].getCreateActions=doc=>doc.docstatus===1?[
  {label:"Purchase Order",path:"/dashboard/purchase-orders/new",prefill:source=>({supplier_quotation:source.name,supplier:source.supplier,supplier_name:source.supplier_name,company:source.company,currency:source.currency,items:mappedItems(source,row=>({supplier_quotation:source.name,supplier_quotation_item:row.name}))})},
]:[];

CONFIG["request-for-quotation"].getCreateActions=doc=>doc.docstatus===1?[
  {label:"Supplier Quotation",path:"/dashboard/supplier-quotations/new",prefill:source=>({request_for_quotation:source.name,supplier:source.suppliers?.[0]?.supplier||"",supplier_name:source.suppliers?.[0]?.supplier_name||"",company:source.company,items:mappedItems(source,row=>({request_for_quotation:source.name,request_for_quotation_item:row.name}))})},
]:[];
