import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import PageHeader from "@/components/shared/PageHeader";
import SearchableSelect from "@/components/shared/SearchableSelect";
import * as service from "@/services/selling/sellingSettingsService";
import * as lookup from "@/services/selling/customerGroupService";
import { getErrorMessage } from "@/utils/errors";
const Field=({label,children})=><div className="field"><label className="label">{label}</label>{children}</div>;
export default function SellingSettingsPage(){const[form,setForm]=useState({}),[options,setOptions]=useState({}),[saving,setSaving]=useState(false);useEffect(()=>{service.get().then(setForm).catch(e=>toast.error(getErrorMessage(e)));Promise.all(["Customer Group","Territory","Price List"].map(async d=>[d,await lookup.getLookupOptions(d)])).then(rows=>setOptions(Object.fromEntries(rows)))},[]);const set=(k,v)=>setForm(old=>({...old,[k]:v}));async function save(e){e.preventDefault();try{setSaving(true);setForm(await service.update(form));toast.success("Selling Settings updated")}catch(error){toast.error(getErrorMessage(error))}finally{setSaving(false)}}return <><PageHeader eyebrow="Selling" title="Selling Settings"/><form className="panel" onSubmit={save}><div className="grid-form p-5"><Field label="Customer Naming By"><select className="input" value={form.cust_master_name||"Customer Name"} onChange={e=>set("cust_master_name",e.target.value)}><option>Customer Name</option><option>Naming Series</option><option>Auto Name</option></select></Field><Field label="Default Customer Group"><SearchableSelect value={form.customer_group||""} onChange={v=>set("customer_group",v)} options={options["Customer Group"]||[]} linkedDoctype="Customer Group"/></Field><Field label="Default Territory"><SearchableSelect value={form.territory||""} onChange={v=>set("territory",v)} options={options.Territory||[]} linkedDoctype="Territory"/></Field><Field label="Default Selling Price List"><SearchableSelect value={form.selling_price_list||""} onChange={v=>set("selling_price_list",v)} options={options["Price List"]||[]} linkedDoctype="Price List"/></Field><Field label="Sales Update Frequency"><select className="input" value={form.sales_update_frequency||"Each Transaction"} onChange={e=>set("sales_update_frequency",e.target.value)}><option>Monthly</option><option>Each Transaction</option><option>Daily</option></select></Field>{[["maintain_same_sales_rate","Maintain Same Sales Rate"],["editable_price_list_rate","Allow Price List Rate Editing"],["allow_multiple_items","Allow Multiple Items"],["allow_item_to_be_added_multiple_times_in_a_transaction","Allow Item Multiple Times"],["hide_tax_id","Hide Tax ID"]].map(([key,label])=><Field key={key} label={label}><label className="flex min-h-10 items-center gap-2"><input type="checkbox" checked={!!Number(form[key])} onChange={e=>set(key,e.target.checked?1:0)}/> Enabled</label></Field>)}</div><div className="flex justify-end p-5"><button className="btn btn-primary" disabled={saving}>{saving?"Saving...":"Save Settings"}</button></div></form></>}
