import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import SearchableSelect from "@/components/shared/SearchableSelect";
import { getErrorMessage } from "@/utils/errors";
import PerformanceChildTable from "./PerformanceChildTable";

const initialValue=field=>field.type==="check"?0:"";
const today=()=>new Date().toISOString().slice(0,10);
const missing=value=>value===undefined||value===null||value==="";
const isRequired=(field,document)=>typeof field.required==="function"?field.required(document):field.required;

function InputField({field,value,onChange,options,document,onRefreshOptions}){
  const readOnly=typeof field.readOnly==="function"?field.readOnly(document):field.readOnly;
  if(readOnly)return <div className="rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground">{missing(value)?"—":String(value)}</div>;
  if(field.type==="link")return <SearchableSelect value={value||""} onChange={onChange} options={options[field.options]||[]} displayField={field.displayField} showId={field.showId} linkedDoctype={field.name==="employee"||field.name==="reviewer"?null:(field.linkedDoctype??null)} label={field.label} placeholder={`Search ${field.label.toLowerCase()}...`} onRefreshOptions={onRefreshOptions} parentDefaults={{company:document.company||options.default_company||""}}/>;
  if(field.type==="select")return <select className="input" value={value||""} onChange={event=>onChange(event.target.value)}><option value="">Select {field.label}</option>{(field.values||[]).map(option=><option key={option}>{option}</option>)}</select>;
  if(field.type==="check")return <label className="flex h-9 items-center gap-2"><input type="checkbox" checked={!!Number(value)} onChange={event=>onChange(event.target.checked?1:0)}/><span className="text-sm">{Number(value)?"Yes":"No"}</span></label>;
  if(field.type==="textarea"||field.type==="code")return <textarea className="input font-mono" rows={field.type==="code"?5:4} value={value||""} onChange={event=>onChange(event.target.value)}/>;
  return <input className="input" type={field.type==="date"?"date":field.type==="datetime"?"datetime-local":field.type==="number"?"number":"text"} min={field.min} max={field.max} step={field.type==="number"?"any":undefined} value={value??""} onChange={event=>onChange(event.target.value)}/>;
}

export default function PerformanceDocumentForm({config,document,onSave}){
  const[form,setForm]=useState({});const[options,setOptions]=useState({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[actionLoading,setActionLoading]=useState(false);
  const visibleFields=useMemo(()=>config.fields.filter(field=>!field.show||field.show(form)),[config.fields,form]);
  const visibleTables=useMemo(()=>(config.tables||[]).filter(table=>!table.show||table.show(form)),[config.tables,form]);
  useEffect(()=>{let active=true;config.service.options().then(value=>active&&setOptions(value||{})).catch(error=>toast.error(getErrorMessage(error))).finally(()=>active&&setLoading(false));return()=>{active=false};},[config]);
  async function refreshOptions(){try{const value=await config.service.options();setOptions(value||{});return value||{};}catch(error){toast.error(getErrorMessage(error));return null;}}
  useEffect(()=>{if(loading)return;const next=Object.fromEntries(config.fields.map(field=>[field.name,document?.[field.name]??initialValue(field)]));for(const table of config.tables||[])next[table.name]=(document?.[table.name]||[]).map(row=>({...row}));if(!document){if(next.company!==undefined)next.company=options.default_company||"";for(const [key,value] of Object.entries(config.defaults||{}))next[key]=typeof value==="function"?value():value;if(next.added_on!==undefined&&!next.added_on)next.added_on=new Date().toISOString().slice(0,16);if(next.promotion_date!==undefined&&!next.promotion_date)next.promotion_date=today();}setForm(next);},[config,document,loading,options.default_company]);
  useEffect(()=>{if(config.key!=="appraisal"||!form.appraisal_template)return;let active=true;config.service.template(form.appraisal_template,form.appraisal_cycle).then(result=>{if(!active)return;setForm(current=>({...current,rate_goals_manually:result.rate_goals_manually??current.rate_goals_manually,goals:result.goals||[],appraisal_kra:result.appraisal_kra||[],self_ratings:result.self_ratings||[]}));}).catch(error=>active&&toast.error(getErrorMessage(error)));return()=>{active=false};},[config,form.appraisal_template,form.appraisal_cycle]);
  useEffect(()=>{if(config.key!=="employeePerformanceFeedback"||!form.appraisal)return;let active=true;config.service.details(form.appraisal).then(result=>{if(active)setForm(current=>({...current,...result,reviewer:current.reviewer||result.reviewer||"",feedback:current.feedback||""}));}).catch(error=>active&&toast.error(getErrorMessage(error)));return()=>{active=false};},[config,form.appraisal]);
  useEffect(()=>{if(config.key!=="energyPointRule"||!form.reference_doctype)return;let active=true;config.service.referenceFields(form.reference_doctype).then(result=>active&&setOptions(current=>({...current,...result}))).catch(error=>active&&toast.error(getErrorMessage(error)));return()=>{active=false};},[config,form.reference_doctype]);
  useEffect(()=>{if(config.key!=="appraisal")return;setForm(current=>{const goals=(current.goals||[]).map(row=>({...row,score_earned:(Number(row.score||0)*Number(row.per_weightage||0))/100}));const total=goals.reduce((sum,row)=>sum+Number(row.score_earned||0),0);const rated=goals.filter(row=>row.score!==""&&row.score!==null&&row.score!==undefined);const average=rated.length?rated.reduce((sum,row)=>sum+Number(row.score||0),0)/rated.length:0;if(JSON.stringify(goals)===JSON.stringify(current.goals||[])&&Number(current.total_score||0)===total&&Number(current.average_score||0)===average)return current;return{...current,goals,total_score:total,average_score:average};});},[config,JSON.stringify(form.goals)]);
  useEffect(()=>{if(config.key!=="employeePerformanceFeedback")return;setForm(current=>{const total=(current.feedback_ratings||[]).reduce((sum,row)=>sum+(Number(row.rating||0)*5*Number(row.per_weightage||0)/100),0);return Number(current.total_score||0)===total?current:{...current,total_score:total};});},[config,JSON.stringify(form.feedback_ratings)]);
  function change(name,value,selectedOption){setForm(current=>{const next={...current,[name]:value};if(name==="employee"){const employee=selectedOption?.name===value?selectedOption:(options.employees||[]).find(row=>row.name===value)||{};next.employee_name=employee.employee_name||"";next.department=employee.department||"";next.company=employee.company||"";next.designation=employee.designation||"";if(config.key==="employeePromotion"){next.salary_currency=employee.salary_currency||"";next.current_ctc=employee.ctc??"";next.promotion_details=[];}}if(name==="reviewer"){const reviewer=selectedOption?.name===value?selectedOption:(options.employees||[]).find(row=>row.name===value)||{};next.reviewer_name=reviewer.employee_name||"";next.reviewer_designation=reviewer.designation||"";}if(name==="appraisal_cycle"){const cycle=selectedOption?.name===value?selectedOption:(options.appraisal_cycles||[]).find(row=>row.name===value)||{};if(next.start_date!==undefined)next.start_date=cycle.start_date||"";if(next.end_date!==undefined)next.end_date=cycle.end_date||"";if(next.rate_goals_manually!==undefined)next.rate_goals_manually=cycle.kra_evaluation_method==="Manual Rating"?1:0;}if(config.key==="goal"&&name==="parent_goal"){const goal=selectedOption?.name===value?selectedOption:(options.goals||[]).find(row=>row.name===value)||{};next.kra=goal.kra||next.kra;next.appraisal_cycle=goal.appraisal_cycle||next.appraisal_cycle;}return next;});}
  async function formAction(){if(config.formAction!=="getAppraisees")return; if(!form.company)return toast.error("Company is required");setActionLoading(true);try{const rows=await config.service.appraisees(form);setForm(current=>({...current,appraisees:rows||[]}));toast.success(`${(rows||[]).length} employee(s) loaded`);}catch(error){toast.error(getErrorMessage(error));}finally{setActionLoading(false);}}
  async function submit(event){event.preventDefault();const required=visibleFields.find(field=>isRequired(field,form)&&missing(form[field.name]));if(required)return toast.error(`${required.label} is required`);if(form.start_date&&form.end_date&&form.start_date>form.end_date)return toast.error("End Date cannot be before Start Date");if(config.key==="appraisal"&&(form.goals||[]).some(row=>Number(row.score||0)>5))return toast.error("Goal Score cannot be greater than 5");for(const table of visibleTables){const rows=form[table.name]||[];if(table.required&&!rows.length)return toast.error(`Add at least one row to ${table.label}`);if(table.weightage&&rows.length){const total=rows.reduce((sum,row)=>sum+Number(row.per_weightage||0),0);if(Math.round(total*100)/100!==100)return toast.error(`${table.label} weightage must total 100%. Current total: ${total}%`);}}setSaving(true);try{await onSave(form);}finally{setSaving(false);}}
  if(loading)return <div className="p-5 text-sm text-muted-foreground">Loading form options…</div>;
  return <form onSubmit={submit}><div className="panel-head"><div className="panel-title">{config.singular} Information</div>{config.formAction==="getAppraisees"&&<button type="button" className="btn btn-secondary" onClick={formAction} disabled={actionLoading}>{actionLoading?"Fetching…":"Get Employees"}</button>}</div><div className="grid-form" style={{padding:"16px 20px 26px"}}>{visibleFields.map(field=><div className="field" key={field.name} style={field.full?{gridColumn:"1 / -1"}:undefined}><label className="label">{field.label}{isRequired(field,form)&&<span className="text-destructive"> *</span>}</label><InputField field={field} value={form[field.name]} onChange={(value,selected)=>change(field.name,value,selected)} options={options} document={form} onRefreshOptions={refreshOptions}/>{field.help&&<p className="mt-1 text-xs text-muted-foreground">{field.help}</p>}</div>)}{visibleTables.map(table=><PerformanceChildTable key={table.name} table={table} rows={form[table.name]||[]} onChange={rows=>change(table.name,rows)} options={options} onRefreshOptions={refreshOptions} context={form} resolveProperty={config.service.property}/>)}</div><div className="flex justify-end gap-2 p-5 pt-0"><button type="button" className="btn btn-secondary" onClick={()=>window.history.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?"Saving...":document?`Update ${config.singular}`:`Create ${config.singular}`}</button></div></form>;
}
