import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import SearchableSelect from "@/components/shared/SearchableSelect";
import { getCompanies, getParentDepartments } from "@/services/hr/departmentService";

export default function DepartmentForm({ department, onSave }) {
  const [form, setForm] = useState({ department_name: "", parent_department: "", company: "", is_group: 0, disabled: 0 });
  const [companies, setCompanies] = useState([]); const [parents, setParents] = useState([]); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([getCompanies(), getParentDepartments()]).then(([companyRows, parentRows]) => { setCompanies((companyRows || []).map((row) => ({ ...row, display_name: row.company_name || row.name }))); setParents((parentRows || []).map((row) => ({ ...row, display_name: row.department_name || row.name }))); }).catch(() => { setCompanies([]); setParents([]); }); }, []);
  useEffect(() => { if (department) setForm({ department_name: department.department_name || "", parent_department: department.parent_department || "", company: department.company || "", is_group: Number(department.is_group || 0), disabled: Number(department.disabled || 0) }); }, [department]);
  const setField = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event) { event.preventDefault(); if (!form.department_name.trim()) return toast.error("Department is required"); if (!form.company) return toast.error("Company is required"); setSaving(true); try { await onSave(form); } finally { setSaving(false); } }
  return <form onSubmit={submit}><div className="panel-head"><div className="panel-title">Department Information</div></div><div style={{ padding: 20 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 20 }}><div style={{ display: "grid", gap: 14, alignContent: "start" }}><div className="field"><label className="label">Department <span style={{ color: "var(--danger)" }}>*</span></label><input className="input" value={form.department_name} onChange={(event) => setField("department_name", event.target.value)} /></div><div className="field"><label className="label">Parent Department</label><SearchableSelect value={form.parent_department} onChange={(value) => setField("parent_department", value)} options={parents} displayField="display_name" label="Parent Department" placeholder="Search group department..." showId /></div></div><div style={{ display: "grid", gap: 14, alignContent: "start" }}><div className="field"><label className="label">Company <span style={{ color: "var(--danger)" }}>*</span></label><SearchableSelect value={form.company} onChange={(value) => setField("company", value)} options={companies} displayField="display_name" label="Company" placeholder="Search company..." showId /></div><label className="flex h-9 items-center gap-2"><input type="checkbox" checked={Boolean(form.is_group)} onChange={(event) => setField("is_group", event.target.checked ? 1 : 0)} /><span className="text-sm">Is Group</span></label><label className="flex h-9 items-center gap-2"><input type="checkbox" checked={Boolean(form.disabled)} onChange={(event) => setField("disabled", event.target.checked ? 1 : 0)} /><span className="text-sm">Disabled</span></label></div></div></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 10, padding: "0 20px 20px" }}><button type="button" className="btn btn-secondary" onClick={() => window.history.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? "Saving..." : department ? "Update Department" : "Create Department"}</button></div></form>;
}
