import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { LogIn, RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import { PageHeader } from "@/components/shared/OriginalPrimitives";
import ConfirmDialog from "@/components/shared/ConfirmDialog";
import { deleteEmployeeCheckin, fetchEmployeeCheckinShift, getEmployeeCheckin } from "@/services/hr/employeeCheckinService";
import { getErrorMessage } from "@/utils/errors";

const Field = ({ label, value }) => <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm font-medium">{value === null || value === undefined || value === "" ? "—" : value}</p></div>;
export default function EmployeeCheckinProfilePage() {
  const { id } = useParams(); const name = decodeURIComponent(id); const nav = useNavigate();
  const [doc, setDoc] = useState(null); const [removeOpen, setRemoveOpen] = useState(false); const [fetching, setFetching] = useState(false);
  async function load() { try { setDoc(await getEmployeeCheckin(name)); } catch (error) { toast.error(getErrorMessage(error)); } }
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [name]);
  async function remove() { try { await deleteEmployeeCheckin(name); toast.success("Employee Checkin deleted"); nav("/dashboard/employee-checkins"); } catch (error) { toast.error(getErrorMessage(error)); } }
  async function fetchShift() { try { setFetching(true); const updated = await fetchEmployeeCheckinShift(name); setDoc((old) => ({ ...old, ...updated })); toast.success(updated.shift ? `Shift updated to ${updated.shift}` : "No valid shift found for this log time"); } catch (error) { toast.error(getErrorMessage(error)); } finally { setFetching(false); } }
  if (!doc) return <div className="muted">Loading employee checkin…</div>;
  return <><PageHeader eyebrow="HR · Attendance" title={doc.employee_name || doc.name} sub={doc.name} button={<div className="flex gap-2">{doc.can_edit && !doc.attendance && <button className="btn btn-secondary" onClick={fetchShift} disabled={fetching}><RefreshCw size={15} className={fetching ? "animate-spin" : ""}/>{fetching ? "Fetching..." : "Fetch Shift"}</button>}{doc.can_edit && <button className="btn btn-secondary" onClick={() => nav(`/dashboard/employee-checkins/${encodeURIComponent(name)}/edit`)}>Edit</button>}{doc.can_delete && <button className="btn btn-danger" onClick={() => setRemoveOpen(true)}>Delete</button>}</div>}/>{doc.offshift && <div className="mb-4 rounded-md border border-amber-300 bg-amber-50 p-4 text-sm font-medium text-amber-900">This check-in is outside assigned shift hours and will not be considered for attendance. Adjust the shift assignment or its time window, then use Fetch Shift again.</div>}<div className="panel"><div className="panel-head"><div className="panel-title"><LogIn size={15}/> Employee Checkin Information</div></div><div className="grid-form" style={{padding:"10px 20px 26px"}}>{[["Employee",doc.employee],["Employee Name",doc.employee_name],["Log Type",doc.log_type],["Time",doc.time],["Shift",doc.shift],["Location / Device ID",doc.device_id],["Skip Auto Attendance",doc.skip_auto_attendance?"Yes":"No"],["Attendance Marked",doc.attendance]].map(([label,value])=><Field key={label} label={label} value={value}/>)}</div>{Number(doc.allow_geolocation_tracking)?<><div className="panel-head"><div className="panel-title">Location</div></div><div className="grid-form" style={{padding:"10px 20px 26px"}}><Field label="Latitude" value={doc.latitude}/><Field label="Longitude" value={doc.longitude}/><Field label="Geolocation" value={doc.geolocation}/></div></>:null}<div className="panel-head"><div className="panel-title">Shift Timings</div></div><div className="grid-form" style={{padding:"10px 20px 26px"}}>{[["Shift Start",doc.shift_start],["Shift End",doc.shift_end],["Shift Actual Start",doc.shift_actual_start],["Shift Actual End",doc.shift_actual_end]].map(([label,value])=><Field key={label} label={label} value={value}/>)}</div></div><ConfirmDialog open={removeOpen} onClose={() => setRemoveOpen(false)} onConfirm={remove} title={`Delete ${doc.name}?`} description="Linked attendance may prevent deletion." confirmLabel="Delete"/></>;
}
