import { useEffect,useMemo,useState } from "react";
import { Pencil,Plus,Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import SearchableSelect from "@/components/shared/SearchableSelect";
import AttachField from "@/components/shared/AttachField";
import RecruitmentChildModal from "./RecruitmentChildModal";
import { today } from "./recruitmentConfig";
import { linkedDoctypeFor, requiredFieldNames, requiredTableNames } from "./fieldUtils";

const ReadOnly=({value})=><div className="flex min-h-[40px] items-center rounded-md bg-muted px-3 py-2 text-sm font-medium text-muted-foreground">{value===undefined||value===null||value===""?"—":String(value)}</div>;
function Control({field,value,onChange,options,disabled}){if(field.type==="link")return <SearchableSelect value={value||""} onChange={onChange} options={options||[]} displayField={field.displayField} showId={field.showId} placeholder={disabled?`Select ${field.depends} first`:`Search ${field.label.toLowerCase()}...`} disabled={disabled} linkedDoctype={linkedDoctypeFor(field)}/>;if(field.type==="select")return <select className="input" value={value||""} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Select...</option>{field.options.map(x=><option key={x}>{x}</option>)}</select>;if(field.type==="check")return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(Number(value))} onChange={e=>onChange(e.target.checked?1:0)}/> Yes</label>;if(field.type==="textarea")return <textarea className="input" rows={5} style={{height:"auto"}} value={value||""} onChange={e=>onChange(e.target.value)}/>;if(field.type==="file"||field.type==="image")return <AttachField value={value||""} onChange={onChange} label={field.label} image={field.type==="image"} disabled={disabled}/>;const type={date:"date",datetime:"datetime-local",time:"time",number:"number",currency:"number",email:"email",rating:"number"}[field.type]||"text";return <input className="input" type={type} min={field.type==="rating"?0:undefined} max={field.type==="rating"?1:undefined} step={field.type==="rating"?0.1:undefined} value={value||""} onChange={e=>onChange(e.target.value)}/>}
export default function RecruitmentForm({config,doc,onSave}){const editing=Boolean(doc);const namingFields=useMemo(()=>config.base==="staffing-plan"?[{name:"name",label:"Staffing Plan Name",type:"text",required:true,immutable:true}]:config.base==="job-requisition"?[{name:"naming_series",label:"Naming Series",type:"select",required:true,default:"HR-HIREQ-",options:["HR-HIREQ-"]}]:[],[config.base]);const fields=useMemo(()=>{const required=requiredFieldNames(config.base);return [...namingFields,...config.fields].map(field=>required.has(field.name)?{...field,required:true}:field)},[namingFields,config.base,config.fields]);const initial=useMemo(()=>Object.fromEntries(fields.map(x=>[x.name,x.default==="today"?today():x.default||""])),[fields]);const[form,setForm]=useState(initial),[options,setOptions]=useState({}),[modal,setModal]=useState(null),[saving,setSaving]=useState(false),[unlockDate,setUnlockDate]=useState(false);useEffect(()=>{if(doc){const next={...initial,...doc};for(const table of config.tables||[])next[table.name]=doc[table.name]||[];setForm(next)}},[doc,initial,config.tables]);useEffect(()=>{const links=[...new Set([...fields,...(config.tables||[]).flatMap(t=>t.fields)].filter(x=>x.type==="link").map(x=>x.doctype))];Promise.all(links.map(async d=>[d,await config.service.getLookupOptions(d)])).then(x=>setOptions(Object.fromEntries(x))).catch(()=>setOptions({}));},[config,fields]);
 const set=(name,value)=>setForm(old=>({...old,[name]:value}));
 async function change(field,value){set(field.name,value);if(config.employeeField===field.name){if(!value){const cleared={};for(const target of Object.values(config.employeeMap||{}))cleared[target]="";setForm(old=>({...old,[field.name]:"",...cleared}));return}const data=await config.service.getEmployeeDetails(value);const mapped={};for(const[source,target]of Object.entries(config.employeeMap||{}))mapped[target]=data[source]||"";setForm(old=>({...old,[field.name]:value,...mapped}));return}const fetchMap=config.base==="interviews"&&field.name==="job_applicant"?{...field.fetch,designation:"designation"}:field.fetch;if(fetchMap&&value){try{const data=await config.service.getLinkedDetails(field.doctype,value,Object.keys(fetchMap));const mapped={};for(const[source,target]of Object.entries(fetchMap))mapped[target]=data[source]||"";if(config.base==="interview-feedback"&&field.name==="interview"&&data.interview_round){const round=await config.service.getLinkedDetails("Interview Round",data.interview_round,["expected_skill_set"]);mapped.skill_assessment=(round.expected_skill_set||[]).map(row=>({skill:row.skill,rating:0}))}setForm(old=>({...old,[field.name]:value,...mapped}));}catch{/* fetch_from is also enforced by Frappe */}}if(config.base==="employee-referrals"&&(field.name==="first_name"||field.name==="last_name"))setForm(old=>({...old,[field.name]:value,full_name:`${field.name==="first_name"?value:old.first_name||""} ${field.name==="last_name"?value:old.last_name||""}`.trim()}));}
 function saveRow(row){const{table,index}=modal;const missing=table.fields.find(x=>x.required&&!row[x.name]);if(missing)return toast.error(`${missing.label} is required`);if(table.name==="staffing_details"){row={...row,total_estimated_cost:Number(row.vacancies||0)*Number(row.estimated_cost_per_position||0)}}setForm(old=>{const rows=index===null?[...(old[table.name]||[]),row]:(old[table.name]||[]).map((x,i)=>i===index?row:x);const next={...old,[table.name]:rows};if(table.name==="staffing_details")next.total_estimated_budget=rows.reduce((sum,x)=>sum+Number(x.total_estimated_cost||0),0);return next});setModal(null)}
 async function submit(e){e.preventDefault();const missing=fields.filter(x=>x.required&&!form[x.name]);const requiredTables=requiredTableNames(config.base);for(const table of config.tables||[])if(requiredTables.has(table.name)&&!(form[table.name]||[]).length)missing.push({label:table.label});if(missing.length){missing.forEach(field=>toast.error(`${field.label} is required`));return}setSaving(true);try{await onSave(form)}finally{setSaving(false)}}
 const sections=[];for(const field of fields){const name=field.section||"Details";let section=sections.find(x=>x.label===name);if(!section){section={label:name,collapsible:field.collapsible,fields:[]};sections.push(section)}section.fields.push(field)}
 return <form onSubmit={submit}>{sections.map(section=><details key={section.label} open={!section.collapsible} className="border-b"><summary className="panel-head cursor-pointer"><span className="panel-title">{section.label}</span></summary><div className="grid-form" style={{padding:"10px 20px 26px"}}>{section.fields.map(field=><div className="field" key={field.name} style={field.full?{gridColumn:"1 / -1"}:undefined}><label className="label">{field.label}{field.required&&<span className="text-destructive"> *</span>}</label>{field.postingLock&&editing&&!unlockDate?<><ReadOnly value={form[field.name]}/><label className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" onChange={e=>setUnlockDate(e.target.checked)}/> Edit {field.label.toLowerCase()}</label></>:field.readOnly||(editing&&field.immutable)?<ReadOnly value={form[field.name]}/>:<Control field={field} value={form[field.name]} onChange={v=>change(field,v)} options={options[field.doctype]} disabled={field.depends&&!form[field.depends]}/>}</div>)}</div></details>)}{(config.tables||[]).map(table=><section key={table.name}><div className="panel-head"><div className="panel-title">{table.label}</div><button type="button" className="btn btn-secondary" onClick={()=>setModal({table,index:null,row:null})}><Plus size={14}/> Add Row</button></div><div className="overflow-x-auto px-5 pb-6"><table className="tbl"><thead><tr>{table.summary.map(name=><th key={name}>{table.fields.find(x=>x.name===name)?.label}</th>)}<th/></tr></thead><tbody>{(form[table.name]||[]).map((row,index)=><tr key={index}>{table.summary.map(name=><td key={name}>{row[name]||"—"}</td>)}<td><div className="flex gap-1"><button type="button" className="btn btn-ghost" onClick={()=>setModal({table,index,row})}><Pencil size={14}/></button><button type="button" className="btn btn-ghost" onClick={()=>setForm(old=>({...old,[table.name]:old[table.name].filter((_,i)=>i!==index)}))}><Trash2 size={14}/></button></div></td></tr>)}{!(form[table.name]||[]).length&&<tr><td colSpan={table.summary.length+1} className="text-muted-foreground">No rows added.</td></tr>}</tbody></table></div></section>)}<div className="flex justify-end gap-2 p-5"><button type="button" className="btn btn-secondary" onClick={()=>history.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?"Saving...":editing?`Update ${config.title}`:`Create ${config.title}`}</button></div><RecruitmentChildModal state={modal} onClose={()=>setModal(null)} onSave={saveRow} options={options}/></form>}
