import * as staffingPlan from "@/services/recruitment/staffingPlanService";
import * as jobRequisition from "@/services/recruitment/jobRequisitionService";
import * as jobOpening from "@/services/recruitment/jobOpeningService";
import * as jobApplicant from "@/services/recruitment/jobApplicantService";
import * as jobOffer from "@/services/recruitment/jobOfferService";
import * as employeeReferral from "@/services/recruitment/employeeReferralService";
import * as interviewType from "@/services/recruitment/interviewTypeService";
import * as interviewRound from "@/services/recruitment/interviewRoundService";
import * as interview from "@/services/recruitment/interviewService";
import * as interviewFeedback from "@/services/recruitment/interviewFeedbackService";
import * as appointmentTemplate from "@/services/recruitment/appointmentLetterTemplateService";
import * as appointmentLetter from "@/services/recruitment/appointmentLetterService";

const f=(name,label,type="text",extra={})=>({name,label,type,...extra});
const employee=(name="employee",label="Employee",extra={})=>f(name,label,"link",{doctype:"Employee",displayField:"employee_name",showId:true,...extra});
const user=(name,label,extra={})=>f(name,label,"link",{doctype:"User",displayField:"full_name",showId:true,...extra});
const termTable={name:"terms",label:"Terms",summary:["title","description"],fields:[f("title","Title","text",{required:true}),f("description","Description","textarea",{required:true,full:true})]};
const colors={green:"success",orange:"warning",yellow:"warning",blue:"info",red:"danger",gray:"neutral",grey:"neutral"};

export const CONFIG={
 "staffing-plan":{title:"Staffing Plan",plural:"Staffing Plans",base:"staffing-plan",service:staffingPlan,submittable:true,titleField:"name",list:["name","company","department","from_date","to_date","total_estimated_budget","docstatus"],filters:["company","department"],fields:[f("company","Company","link",{doctype:"Company",required:true}),f("department","Department","link",{doctype:"Department",quick:true,depends:"company"}),f("from_date","From Date","date",{required:true}),f("to_date","To Date","date",{required:true}),f("total_estimated_budget","Total Estimated Budget","currency",{readOnly:true})],tables:[{name:"staffing_details",label:"Staffing Details",summary:["designation","vacancies","estimated_cost_per_position","total_estimated_cost"],fields:[f("designation","Designation","link",{doctype:"Designation",required:true,quick:true}),f("vacancies","Vacancies","number"),f("estimated_cost_per_position","Estimated Cost Per Position","number"),f("total_estimated_cost","Total Estimated Cost","currency",{readOnly:true}),f("current_count","Current Count","number",{readOnly:true}),f("current_openings","Current Openings","number",{readOnly:true}),f("number_of_positions","Number of Positions","number",{readOnly:true})]}]},
 "job-requisition":{title:"Job Requisition",plural:"Job Requisitions",base:"job-requisition",service:jobRequisition,titleField:"designation",statusField:"status",statuses:["Pending","Open & Approved","Rejected","Filled","On Hold","Cancelled"],statusColors:{Pending:"warning","Open & Approved":"info",Rejected:"danger",Filled:"success","On Hold":"neutral",Cancelled:"neutral"},list:["name","designation","no_of_positions","requested_by_name","expected_by","status"],filterKeys:["designation","department","company","requested_by"],connectionItems:[{key:"job_openings",label:"Job Openings",path:"/dashboard/job-opening",filter:"job_requisition"}],employeeField:"requested_by",employeeMap:{employee_name:"requested_by_name",department:"requested_by_dept",designation:"requested_by_designation",company:"company"},fields:[f("designation","Designation","link",{doctype:"Designation",required:true,quick:true}),f("department","Department","link",{doctype:"Department",quick:true,depends:"company"}),f("no_of_positions","No. of Positions","number",{required:true}),f("expected_compensation","Expected Compensation","currency",{required:true}),f("company","Company","link",{doctype:"Company",required:true}),f("status","Status","select",{required:true,default:"Pending",options:["Pending","Open & Approved","Rejected","Filled","On Hold","Cancelled"]}),employee("requested_by","Requested By"),f("requested_by_name","Requested By (Name)","text",{readOnly:true}),f("requested_by_dept","Requested By Department","text",{readOnly:true}),f("requested_by_designation","Requested By Designation","text",{readOnly:true}),f("posting_date","Posting Date","date",{required:true,default:"today"}),f("expected_by","Expected By","date"),f("completed_on","Completed On","date"),f("description","Job Description","textarea",{required:true,full:true,section:"Job Description"}),f("reason_for_requesting","Reason for Requesting","textarea",{full:true,section:"Job Description"})]},
 "job-opening":{title:"Job Opening",plural:"Job Openings",base:"job-opening",service:jobOpening,titleField:"job_title",statusField:"status",statuses:["Open","Closed"],statusColors:{Open:"success",Closed:"neutral"},list:["name","job_title","designation","company","department","closes_on","status"],filterKeys:["designation","department","company","job_requisition"],connectionItems:[{key:"job_applicants",label:"Job Applicants",path:"/dashboard/job-applicants",filter:"job_title"}],fields:[f("job_title","Job Title","text",{required:true}),f("designation","Designation","link",{doctype:"Designation",required:true,quick:true}),f("status","Status","select",{default:"Open",options:["Open","Closed"]}),f("posted_on","Posted On","datetime"),f("closes_on","Closes On","date"),f("closed_on","Closed On","date"),f("company","Company","link",{doctype:"Company",required:true}),f("department","Department","link",{doctype:"Department",quick:true,depends:"company"}),f("employment_type","Employment Type","link",{doctype:"Employment Type"}),f("location","Location","link",{doctype:"Branch"}),f("staffing_plan","Staffing Plan","link",{doctype:"Staffing Plan",quick:true,readOnly:true}),f("job_requisition","Job Requisition","link",{doctype:"Job Requisition",readOnly:true}),f("publish","Publish on Website","check"),f("route","Route"),f("description","Description","textarea",{full:true,section:"Description"}),f("currency","Currency","link",{doctype:"Currency",section:"Salary Range",collapsible:true}),f("lower_range","Lower Range","currency",{section:"Salary Range"}),f("upper_range","Upper Range","currency",{section:"Salary Range"}),f("salary_per","Salary Paid Per","select",{section:"Salary Range",options:["Month","Year"]}),f("publish_salary_range","Publish Salary Range","check",{section:"Salary Range"})]},
 "job-applicant":{title:"Job Applicant",plural:"Job Applicants",base:"job-applicants",service:jobApplicant,titleField:"applicant_name",statusField:"status",statuses:["Open","Replied","Accepted","Rejected","Hold"],statusColors:{Accepted:"success",Open:"warning",Replied:"warning",Hold:"danger",Rejected:"danger"},list:["name","applicant_name","email_id","job_title","designation","applicant_rating","status"],filterKeys:["job_title","designation"],connectionItems:[{key:"job_offers",label:"Job Offers",path:"/dashboard/job-offers",filter:"job_applicant"},{key:"interviews",label:"Interviews",path:"/dashboard/interviews",filter:"job_applicant"},{key:"employee_referrals",label:"Employee Referrals",path:"/dashboard/employee-referrals",filter:"email"}],fields:[f("applicant_name","Applicant Name","text",{required:true}),f("email_id","Email Address","email",{required:true}),f("phone_number","Phone Number"),f("country","Country","link",{doctype:"Country"}),f("job_title","Job Opening","link",{doctype:"Job Opening",displayField:"job_title",showId:true,quick:true,fetch:{designation:"designation"}}),f("designation","Designation","link",{doctype:"Designation",quick:true}),f("status","Status","select",{required:true,default:"Open",options:["Open","Replied","Rejected","Hold","Accepted"]}),f("source","Source","link",{doctype:"Job Applicant Source"}),employee("source_name","Source Employee"),f("applicant_rating","Applicant Rating","rating"),f("cover_letter","Cover Letter","textarea",{full:true,section:"Resume"}),f("resume_attachment","Resume Attachment","file",{section:"Resume"}),f("resume_link","Resume Link","text",{section:"Resume"}),f("currency","Currency","link",{doctype:"Currency",section:"Salary Expectation"}),f("lower_range","Lower Range","currency",{section:"Salary Expectation"}),f("upper_range","Upper Range","currency",{section:"Salary Expectation"})]},
 "job-offer":{title:"Job Offer",plural:"Job Offers",base:"job-offers",service:jobOffer,submittable:true,titleField:"applicant_name",statusField:"status",statuses:["Awaiting Response","Accepted","Rejected"],statusColors:{Accepted:"success","Awaiting Response":"warning",Rejected:"danger"},list:["name","applicant_name","designation","company","offer_date","status","docstatus"],filterKeys:["job_applicant","designation","company"],connectionItems:[{key:"employee_onboardings",label:"Employee Onboarding",path:"/dashboard/employee-onboarding",filter:"job_offer"}],fields:[f("job_applicant","Job Applicant","link",{doctype:"Job Applicant",displayField:"applicant_name",showId:true,required:true,fetch:{applicant_name:"applicant_name",email_id:"applicant_email",designation:"designation"}}),f("applicant_name","Applicant Name","text",{readOnly:true,required:true}),f("applicant_email","Applicant Email","text",{readOnly:true}),f("status","Status","select",{default:"Awaiting Response",options:["Awaiting Response","Accepted","Rejected"]}),f("offer_date","Offer Date","date",{required:true,postingLock:true}),f("designation","Designation","link",{doctype:"Designation",required:true,quick:true}),f("company","Company","link",{doctype:"Company",required:true}),f("terms","Terms and Conditions","textarea",{full:true,section:"Terms"})],tables:[{name:"offer_terms",label:"Job Offer Terms",summary:["offer_term","value"],fields:[f("offer_term","Offer Term","link",{doctype:"Offer Term",required:true}),f("value","Value / Description","textarea",{required:true})]}]},
 "employee-referral":{title:"Employee Referral",plural:"Employee Referrals",base:"employee-referrals",service:employeeReferral,submittable:true,titleField:"full_name",statusField:"status",statuses:["Pending","In Process","Accepted","Rejected"],statusColors:{Pending:"neutral","In Process":"warning",Accepted:"success",Rejected:"danger"},list:["name","full_name","email","for_designation","referrer_name","date","status","docstatus"],filterKeys:["for_designation","referrer"],employeeField:"referrer",employeeMap:{employee_name:"referrer_name",department:"department"},fields:[f("first_name","First Name","text",{required:true}),f("last_name","Last Name","text",{required:true}),f("full_name","Full Name","text",{readOnly:true}),f("date","Date","date",{required:true,default:"today"}),f("status","Status","select",{readOnly:true,default:"Pending",options:["Pending","In Process","Accepted","Rejected"]}),f("for_designation","For Designation","link",{doctype:"Designation",required:true,quick:true}),f("email","Email","email",{required:true}),f("contact_no","Contact No."),f("current_employer","Current Employer"),f("current_job_title","Current Job Title"),f("resume","Resume","file"),f("resume_link","Resume Link"),employee("referrer","Referrer"),f("referrer_name","Referrer Name","text",{readOnly:true}),f("department","Department","text",{readOnly:true}),f("is_applicable_for_referral_bonus","Applicable for Referral Bonus","check"),f("qualification_reason","Why is this candidate qualified?","textarea",{full:true,section:"Additional Information"}),f("work_references","Work References","textarea",{full:true,section:"Additional Information"})]},
 "interview-type":{title:"Interview Type",plural:"Interview Types",base:"interview-types",service:interviewType,titleField:"name",list:["name","description","modified"],connectionItems:[{key:"interview_rounds",label:"Interview Rounds",path:"/dashboard/interview-rounds",filter:"interview_type"}],fields:[f("name","Interview Type","text",{required:true,immutable:true}),f("description","Description","textarea",{full:true})]},
 "interview-round":{title:"Interview Round",plural:"Interview Rounds",base:"interview-rounds",service:interviewRound,titleField:"round_name",list:["round_name","interview_type","designation","expected_average_rating"],filterKeys:["interview_type","designation"],connectionItems:[{key:"interviews",label:"Interviews",path:"/dashboard/interviews",filter:"interview_round"}],fields:[f("round_name","Round Name","text",{required:true,immutable:true}),f("interview_type","Interview Type","link",{doctype:"Interview Type",quick:true}),f("designation","Designation","link",{doctype:"Designation",quick:true}),f("expected_average_rating","Expected Average Rating","rating")],tables:[{name:"interviewers",label:"Interviewers",summary:["user"],fields:[user("user","User")]},{name:"expected_skill_set",label:"Expected Skillset",summary:["skill","description"],fields:[f("skill","Skill","link",{doctype:"Skill",required:true}),f("description","Description","textarea",{readOnly:true})]}]},
 "interview":{title:"Interview",plural:"Interviews",base:"interviews",service:interview,submittable:true,titleField:"job_applicant",statusField:"status",statuses:["Pending","Under Review","Cleared","Rejected"],statusColors:{Pending:"warning","Under Review":"info",Cleared:"success",Rejected:"danger"},list:["name","job_applicant","interview_round","designation","scheduled_on","from_time","to_time","average_rating","status"],filterKeys:["job_applicant","interview_round","designation"],connectionItems:[{key:"interview_feedback",label:"Interview Feedback",path:"/dashboard/interview-feedback",filter:"interview"}],fields:[f("interview_round","Interview Round","link",{doctype:"Interview Round",required:true,quick:true,fetch:{designation:"designation",expected_average_rating:"expected_average_rating"}}),f("job_applicant","Job Applicant","link",{doctype:"Job Applicant",displayField:"applicant_name",showId:true,required:true,fetch:{job_title:"job_opening",resume_link:"resume_link"}}),f("job_opening","Job Opening","text",{readOnly:true}),f("designation","Designation","text",{readOnly:true}),f("status","Status","select",{required:true,default:"Pending",options:["Pending","Under Review","Cleared","Rejected"]}),f("scheduled_on","Scheduled On","date",{required:true}),f("from_time","From Time","time",{required:true}),f("to_time","To Time","time",{required:true}),f("resume_link","Resume Link"),f("expected_average_rating","Expected Average Rating","rating",{readOnly:true,section:"Ratings"}),f("average_rating","Obtained Average Rating","rating",{readOnly:true,section:"Ratings"}),f("interview_summary","Interview Summary","textarea",{full:true,section:"Interview Summary",collapsible:true})],tables:[{name:"interview_details",label:"Interviewers",summary:["interviewer"],fields:[user("interviewer","Interviewer")]}]},
 "interview-feedback":{title:"Interview Feedback",plural:"Interview Feedback",base:"interview-feedback",service:interviewFeedback,submittable:true,titleField:"interviewer",statusField:"result",statuses:["Cleared","Rejected"],statusColors:{Cleared:"success",Rejected:"danger"},list:["name","interview","interview_round","job_applicant","interviewer","average_rating","result","docstatus"],filterKeys:["interview","interviewer"],fields:[f("interview","Interview","link",{doctype:"Interview",required:true,fetch:{interview_round:"interview_round",job_applicant:"job_applicant"}}),f("interview_round","Interview Round","text",{readOnly:true,required:true}),f("job_applicant","Job Applicant","text",{readOnly:true}),user("interviewer","Interviewer"),f("result","Result","select",{required:true,options:["Cleared","Rejected"]}),f("average_rating","Average Rating","rating",{readOnly:true}),f("feedback","Feedback","textarea",{full:true,section:"Feedback"})],tables:[{name:"skill_assessment",label:"Skill Assessment",summary:["skill","rating"],fields:[f("skill","Skill","text",{required:true,readOnly:true}),f("rating","Rating","rating",{required:true})]}]},
 "appointment-letter-template":{title:"Appointment Letter Template",plural:"Appointment Letter Templates",base:"appointment-letter-templates",service:appointmentTemplate,titleField:"template_name",list:["template_name","introduction","modified"],connectionItems:[{key:"appointment_letters",label:"Appointment Letters",path:"/dashboard/appointment-letters",filter:"appointment_letter_template"}],fields:[f("template_name","Template Name","text",{required:true,immutable:true}),f("introduction","Introduction","textarea",{required:true,full:true}),f("closing_notes","Closing Notes","textarea",{full:true})],tables:[termTable]},
 "appointment-letter":{title:"Appointment Letter",plural:"Appointment Letters",base:"appointment-letters",service:appointmentLetter,titleField:"applicant_name",list:["name","applicant_name","company","appointment_date","appointment_letter_template"],filterKeys:["job_applicant","company","appointment_letter_template"],fields:[f("job_applicant","Job Applicant","link",{doctype:"Job Applicant",displayField:"applicant_name",showId:true,required:true,fetch:{applicant_name:"applicant_name"}}),f("applicant_name","Applicant Name","text",{readOnly:true,required:true}),f("company","Company","link",{doctype:"Company",required:true}),f("appointment_date","Appointment Date","date",{required:true}),f("appointment_letter_template","Appointment Letter Template","link",{doctype:"Appointment Letter Template",required:true,quick:true,fetch:{introduction:"introduction",closing_notes:"closing_notes",terms:"terms"}}),f("introduction","Introduction","textarea",{required:true,full:true}),f("closing_notes","Closing Notes","textarea",{full:true})],tables:[termTable]}
};

export const badgeTone=(config,status)=>config.statusColors?.[status]||colors[status]||"neutral";
export const labelize=value=>String(value||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export const today=()=>new Date().toISOString().slice(0,10);
