import * as quotation from "@/services/selling/quotationService";
import * as salesOrder from "@/services/selling/salesOrderService";
import * as blanketOrder from "@/services/selling/blanketOrderService";
import * as salesPartner from "@/services/selling/salesPartnerService";
import * as salesPerson from "@/services/selling/salesPersonService";
import * as customerGroup from "@/services/selling/customerGroupService";
import * as territory from "@/services/selling/territoryService";
import * as leadSource from "@/services/selling/leadSourceService";
import * as campaign from "@/services/selling/campaignService";
import * as salesTaxesTemplate from "@/services/selling/salesTaxesTemplateService";

const f = (name, label, type = "text", extra = {}) => ({ name, label, type, ...extra });
const company = () => f("company", "Company", "link", { doctype: "Company", required: true });
const customer = (extra = {}) => f("customer", "Customer", "link", { doctype: "Customer", displayField: "customer_name", showId: true, required: true, ...extra });
const item = (extra = {}) => f("item_code", "Item", "link", { doctype: "Item", displayField: "item_name", showId: true, required: true, fetch: { item_name: "item_name", stock_uom: "stock_uom", uom: "stock_uom" }, ...extra });
const itemFields = [item(), f("item_name", "Item Name", "text", { readOnly: true }), f("description", "Description", "textarea"), f("qty", "Quantity", "number", { required: true }), f("uom", "UOM", "link", { doctype: "UOM", required: true }), f("stock_uom", "Stock UOM", "text", { readOnly: true }), f("conversion_factor", "Conversion Factor", "number", { default: 1 }), f("delivery_date", "Delivery Date", "date"), f("warehouse", "Warehouse", "link", { doctype: "Warehouse" }), f("rate", "Rate", "currency"), f("amount", "Amount", "currency", { readOnly: true })];
const taxes = { name: "taxes", label: "Taxes", summary: ["charge_type", "account_head", "rate", "tax_amount"], fields: [f("charge_type", "Charge Type", "select", { options: ["Actual", "On Net Total", "On Previous Row Amount", "On Previous Row Total", "On Item Quantity"] }), f("account_head", "Account Head", "link", { doctype: "Account" }), f("description", "Description"), f("rate", "Rate", "number"), f("tax_amount", "Tax Amount", "currency")] };
const transaction = (title, plural, base, service, fields, tables, statuses) => ({ eyebrow: "Selling", title, plural, base, service, defaultCompany: true, submittable: true, titleField: "name", statusField: statuses ? "status" : undefined, statuses: statuses || [], statusColors: { Draft: "neutral", Open: "warning", Replied: "info", "Partially Ordered": "warning", Ordered: "success", Lost: "neutral", Expired: "neutral", "On Hold": "warning", "To Deliver and Bill": "warning", "To Bill": "info", "To Deliver": "warning", Completed: "success", Closed: "success", Cancelled: "danger" }, list: ["name", ...fields.filter((field) => ["party_name", "customer_name", "company", "transaction_date", "delivery_date", "valid_till", "from_date", "to_date", "grand_total", "status"].includes(field.name)).map((field) => field.name), "docstatus"], fields, tables });

const quotationStatuses = ["Draft", "Open", "Replied", "Partially Ordered", "Ordered", "Lost", "Cancelled", "Expired"];
const orderStatuses = ["Draft", "On Hold", "To Deliver and Bill", "To Bill", "To Deliver", "Completed", "Cancelled", "Closed"];

export const CONFIG = {
  quotation: Object.assign(transaction("Quotation", "Quotations", "quotations", quotation, [
    f("naming_series", "Series", "select", { required: true, default: "SAL-QTN-.YYYY.-", options: ["SAL-QTN-.YYYY.-"] }),
    f("quotation_to", "Quotation To", "select", { required: true, default: "Customer", options: ["Customer", "Lead"] }),
    f("party_name", "Party", "link", { dynamicDoctype: "quotation_to", dynamicDoctypes: ["Customer", "Lead"], required: true, fetchByDoctype: { Customer: { customer_name: "customer_name" }, Lead: { lead_name: "customer_name" } } }),
    f("customer_name", "Party Name", "text", { readOnly: true }), company(),
    f("transaction_date", "Date", "date", { required: true, default: "today", postingLock: true }), f("valid_till", "Valid Till", "date"),
    f("order_type", "Order Type", "select", { required: true, default: "Sales", options: ["Sales", "Maintenance", "Shopping Cart"] }),
    f("currency", "Currency", "link", { doctype: "Currency", required: true, section: "Currency and Price List", collapsible: true }), f("conversion_rate", "Exchange Rate", "number", { required: true, default: 1, section: "Currency and Price List" }), f("selling_price_list", "Price List", "link", { doctype: "Price List", required: true, section: "Currency and Price List" }),
    f("taxes_and_charges", "Sales Taxes Template", "link", { doctype: "Sales Taxes and Charges Template", section: "Taxes and Charges", collapsible: true }), f("additional_discount_percentage", "Additional Discount %", "number", { section: "Totals", collapsible: true }), f("discount_amount", "Discount Amount", "currency", { section: "Totals" }), f("net_total", "Net Total", "currency", { readOnly: true, section: "Totals" }), f("grand_total", "Grand Total", "currency", { readOnly: true, section: "Totals" }), f("tc_name", "Terms and Conditions", "link", { doctype: "Terms and Conditions", section: "Terms", collapsible: true }), f("terms", "Terms", "textarea", { section: "Terms", full: true }), f("status", "Status", "select", { default: "Draft", options: quotationStatuses }),
  ], [{ name: "items", label: "Items", summary: ["item_code", "qty", "uom", "rate", "amount"], fields: itemFields }, taxes], quotationStatuses), { connectionItems: [{ key: "sales_orders", label: "Sales Orders", path: "/dashboard/sales-orders", filter: "quotation" }] }),
  "sales-order": Object.assign(transaction("Sales Order", "Sales Orders", "sales-orders", salesOrder, [
    f("naming_series", "Series", "select", { required: true, default: "SAL-ORD-.YYYY.-", options: ["SAL-ORD-.YYYY.-"] }), customer({ fetch: { customer_name: "customer_name", tax_id: "tax_id" } }), f("customer_name", "Customer Name", "text", { readOnly: true }), company(), f("transaction_date", "Order Date", "date", { required: true, default: "today", postingLock: true }), f("delivery_date", "Delivery Date", "date"), f("order_type", "Order Type", "select", { required: true, default: "Sales", options: ["Sales", "Maintenance", "Shopping Cart"] }), f("currency", "Currency", "link", { doctype: "Currency", required: true, section: "Currency and Price List", collapsible: true }), f("conversion_rate", "Exchange Rate", "number", { required: true, default: 1, section: "Currency and Price List" }), f("selling_price_list", "Price List", "link", { doctype: "Price List", required: true, section: "Currency and Price List" }), f("taxes_and_charges", "Sales Taxes Template", "link", { doctype: "Sales Taxes and Charges Template", section: "Taxes and Charges", collapsible: true }), f("additional_discount_percentage", "Additional Discount %", "number", { section: "Totals", collapsible: true }), f("discount_amount", "Discount Amount", "currency", { section: "Totals" }), f("net_total", "Net Total", "currency", { readOnly: true, section: "Totals" }), f("grand_total", "Grand Total", "currency", { readOnly: true, section: "Totals" }), f("sales_partner", "Sales Partner", "link", { doctype: "Sales Partner", section: "Sales Team", collapsible: true }), f("commission_rate", "Commission Rate", "number", { readOnly: true, section: "Sales Team" }), f("tc_name", "Terms and Conditions", "link", { doctype: "Terms and Conditions", section: "Terms", collapsible: true }), f("terms", "Terms", "textarea", { section: "Terms", full: true }), f("status", "Status", "select", { default: "Draft", options: orderStatuses }),
  ], [{ name: "items", label: "Items", summary: ["item_code", "qty", "uom", "delivery_date", "rate", "amount"], fields: itemFields }, taxes, { name: "sales_team", label: "Sales Team", summary: ["sales_person", "allocated_percentage", "commission_rate"], fields: [f("sales_person", "Sales Person", "link", { doctype: "Sales Person", required: true, fetch: { commission_rate: "commission_rate" } }), f("contact_no", "Contact No"), f("allocated_percentage", "Allocated %", "number"), f("allocated_amount", "Allocated Amount", "currency", { readOnly: true }), f("commission_rate", "Commission Rate", "number", { readOnly: true }), f("incentives", "Incentives", "currency", { readOnly: true })] }], orderStatuses), { filterKeys: ["sales_invoice"], connectionItems: [{ key: "sales_invoices", label: "Sales Invoices", path: "/dashboard/sales-invoices", filter: "sales_order" }, { key: "material_requests", label: "Material Requests", path: "/dashboard/material-requests", filter: "sales_order" }, { key: "purchase_orders", label: "Purchase Orders", path: "/dashboard/purchase-orders", filter: "sales_order" }, { key: "blanket_orders", label: "Blanket Orders", path: "/dashboard/blanket-orders", filter: "sales_order" }, { key: "quotations", label: "Quotations", path: "/dashboard/quotations", filter: "sales_order" }, { key: "payment_entries", label: "Payment Entries", path: "/dashboard/payment-entries?reference_doctype=Sales%20Order", filter: "reference_name" }, { key: "journal_entries", label: "Journal Entries", path: "/dashboard/journal-entries?reference_type=Sales%20Order", filter: "reference_name" }] }),
  "blanket-order": transaction("Blanket Order", "Blanket Orders", "blanket-orders", blanketOrder, [f("naming_series", "Series", "select", { required: true, default: "MFG-BLR-.YYYY.-", options: ["MFG-BLR-.YYYY.-"] }), f("blanket_order_type", "Type", "select", { required: true, options: ["Selling", "Purchasing"] }), customer({ required: false, fetch: { customer_name: "customer_name" } }), f("customer_name", "Customer Name", "text", { readOnly: true }), f("supplier", "Supplier", "link", { doctype: "Supplier", displayField: "supplier_name", showId: true, fetch: { supplier_name: "supplier_name" } }), f("supplier_name", "Supplier Name", "text", { readOnly: true }), company(), f("from_date", "From Date", "date", { required: true }), f("to_date", "To Date", "date", { required: true }), f("tc_name", "Terms and Conditions", "link", { doctype: "Terms and Conditions", section: "Terms", collapsible: true }), f("terms", "Terms", "textarea", { section: "Terms", full: true })], [{ name: "items", label: "Items", summary: ["item_code", "qty", "rate", "ordered_qty"], fields: [item(), f("item_name", "Item Name", "text", { readOnly: true }), f("qty", "Quantity", "number"), f("rate", "Rate", "currency", { required: true }), f("ordered_qty", "Ordered Quantity", "number", { readOnly: true })] }]),
  "sales-partner": { eyebrow: "Selling", title: "Sales Partner", plural: "Sales Partners", base: "sales-partners", service: salesPartner, titleField: "partner_name", list: ["name", "partner_type", "territory", "commission_rate"], fields: [f("partner_name", "Partner Name", "text", { required: true, immutable: true }), f("partner_type", "Partner Type", "link", { doctype: "Sales Partner Type" }), f("territory", "Territory", "link", { doctype: "Territory", required: true }), f("commission_rate", "Commission Rate", "number", { required: true }), f("show_in_website", "Show in Website", "check"), f("partner_website", "Website")] },
  "sales-person": { eyebrow: "Selling", title: "Sales Person", plural: "Sales Persons", base: "sales-persons", service: salesPerson, titleField: "sales_person_name", list: ["name", "parent_sales_person", "is_group", "employee", "enabled"], fields: [f("sales_person_name", "Sales Person Name", "text", { required: true, immutable: true }), f("parent_sales_person", "Parent Sales Person", "link", { doctype: "Sales Person" }), f("is_group", "Is Group", "check", { required: true }), f("employee", "Employee", "link", { doctype: "Employee", displayField: "employee_name", showId: true }), f("department", "Department", "link", { doctype: "Department", readOnly: true }), f("commission_rate", "Commission Rate", "number"), f("enabled", "Enabled", "check", { default: 1 })] },
  "customer-group": { eyebrow: "Selling", title: "Customer Group", plural: "Customer Groups", base: "customer-groups", service: customerGroup, titleField: "customer_group_name", list: ["name", "parent_customer_group", "is_group"], connectionItems: [{ key: "customers", label: "Customers", path: "/dashboard/customers", filter: "customer_group" }], fields: [f("customer_group_name", "Customer Group Name", "text", { required: true, immutable: true }), f("parent_customer_group", "Parent Customer Group", "link", { doctype: "Customer Group" }), f("is_group", "Is Group", "check"), f("default_price_list", "Default Price List", "link", { doctype: "Price List" }), f("payment_terms", "Payment Terms", "link", { doctype: "Payment Terms Template" })] },
  territory: { eyebrow: "Selling", title: "Territory", plural: "Territories", base: "territories", service: territory, titleField: "territory_name", list: ["name", "parent_territory", "is_group", "territory_manager"], connectionItems: [{ key: "customers", label: "Customers", path: "/dashboard/customers", filter: "territory" }], fields: [f("territory_name", "Territory Name", "text", { required: true, immutable: true }), f("parent_territory", "Parent Territory", "link", { doctype: "Territory" }), f("is_group", "Is Group", "check"), f("territory_manager", "Territory Manager", "link", { doctype: "Sales Person" })] },
  "lead-source": { eyebrow: "Selling", title: "Lead Source", plural: "Lead Sources", base: "lead-sources", service: leadSource, titleField: "source_name", list: ["name", "source_name"], fields: [f("source_name", "Source Name", "text", { required: true, immutable: true })] },
  campaign: { eyebrow: "Selling", title: "Campaign", plural: "Campaigns", base: "campaigns", service: campaign, titleField: "campaign_name", list: ["name", "campaign_name", "description"], fields: [f("naming_series", "Series", "select", { default: "SAL-CAM-.YYYY.-", options: ["SAL-CAM-.YYYY.-"] }), f("campaign_name", "Campaign Name", "text", { required: true }), f("description", "Description", "textarea", { full: true })] },
  "sales-taxes-template": { eyebrow: "Selling", defaultCompany: true, title: "Sales Taxes and Charges Template", plural: "Sales Taxes and Charges Templates", base: "sales-taxes-templates", service: salesTaxesTemplate, titleField: "title", list: ["name", "title", "company", "is_default", "disabled"], fields: [f("title", "Title", "text", { required: true }), company(), f("is_default", "Default", "check"), f("disabled", "Disabled", "check"), f("tax_category", "Tax Category", "link", { doctype: "Tax Category" })], tables: [taxes] },
};

CONFIG["blanket-order"].filterKeys = ["sales_order"];
CONFIG["sales-order"].filterKeys = ["sales_invoice", "quotation", "fee_schedule"];

const mappedItems = (doc, extra = () => ({})) => (doc.items || []).map((row) => ({ item_code: row.item_code, item_name: row.item_name, description: row.description, qty: row.qty, uom: row.uom, stock_uom: row.stock_uom, conversion_factor: row.conversion_factor || 1, delivery_date: row.delivery_date, warehouse: row.warehouse, rate: row.rate, amount: row.amount, ...extra(row) }));
CONFIG.quotation.getCreateActions = (doc) => doc.docstatus === 1 ? [{ label: "Sales Order", path: "/dashboard/sales-orders/new", prefill: (source) => ({ quotation: source.name, customer: source.party_name, customer_name: source.customer_name || source.party_name, company: source.company, currency: source.currency, selling_price_list: source.selling_price_list, conversion_rate: source.conversion_rate || 1, items: mappedItems(source, (row) => ({ prevdoc_docname: source.name, quotation_item: row.name })) }) }] : [];
CONFIG["sales-order"].getStatusActions = (doc) => doc.docstatus === 1 ? [{ label: doc.status === "Closed" ? "Unstop" : "Stop", run: (name) => salesOrder.setStatus(name, doc.status === "Closed" ? "Draft" : "Closed"), success: doc.status === "Closed" ? "Sales Order reopened" : "Sales Order stopped" }] : [];
CONFIG["sales-order"].getCreateActions = (doc) => doc.docstatus === 1 && doc.status !== "Closed" ? [
  { label: "Sales Invoice", path: "/dashboard/sales-invoices/new", prefill: (source) => ({ sales_order: source.name, customer: source.customer, customer_name: source.customer_name, company: source.company, currency: source.currency, items: mappedItems(source, (row) => ({ sales_order: source.name, so_detail: row.name })) }) },
  { label: "Payment", path: "/dashboard/payment-entries/new", prefill: (source) => ({ payment_type: "Receive", party_type: "Customer", party: source.customer, party_name: source.customer_name, company: source.company, reference: source.name, reference_doctype: "Sales Order", reference_name: source.name }) },
  { label: "Material Request", path: "/dashboard/material-requests/new", prefill: (source) => ({ material_request_type: "Material Transfer", company: source.company, schedule_date: source.delivery_date, sales_order: source.name, items: mappedItems(source, (row) => ({ sales_order: source.name, sales_order_item: row.name })) }) },
  { label: "Purchase Order", path: "/dashboard/purchase-orders/new", prefill: (source) => ({ company: source.company, schedule_date: source.delivery_date, sales_order: source.name, items: mappedItems(source, (row) => ({ sales_order: source.name, sales_order_item: row.name })) }) },
] : [];
