import { callMethod } from "../../frappeClient";
const NS = "education_extension.staff_portal_api.hr.leaves.compensatory_leave_request_api";
export const getCompensatoryLeaveRequests=(params={})=>callMethod(`${NS}.get_compensatory_leave_requests`,params);
export const getCompensatoryLeaveRequest=(name)=>callMethod(`${NS}.get_compensatory_leave_request`,{name});
export const createCompensatoryLeaveRequest=(data)=>callMethod(`${NS}.create_compensatory_leave_request`,{data});
export const updateCompensatoryLeaveRequest=(name,data)=>callMethod(`${NS}.update_compensatory_leave_request`,{name,data});
export const deleteCompensatoryLeaveRequest=(name)=>callMethod(`${NS}.delete_compensatory_leave_request`,{name});
export const submitCompensatoryLeaveRequest=(name)=>callMethod(`${NS}.submit_compensatory_leave_request`,{name});
export const cancelCompensatoryLeaveRequest=(name)=>callMethod(`${NS}.cancel_compensatory_leave_request`,{name});
export const getCompensatoryEmployees=()=>callMethod(`${NS}.get_employees`);
export const getCompensatoryLeaveTypes=()=>callMethod(`${NS}.get_compensatory_leave_types`);
export const getCompensatoryDepartments=()=>callMethod(`${NS}.get_departments`);
