import { callMethod } from "../../frappeClient";
const NS = "education_extension.staff_portal_api.hr.leaves.leave_application_api";
export const getLeaveApplications = (params={}) => callMethod(`${NS}.get_leave_applications`, params);
export const getLeaveApplication = (name) => callMethod(`${NS}.get_leave_application`, {name});
export const createLeaveApplication = (data) => callMethod(`${NS}.create_leave_application`, {data});
export const updateLeaveApplication = (name,data) => callMethod(`${NS}.update_leave_application`, {name,data});
export const deleteLeaveApplication = (name) => callMethod(`${NS}.delete_leave_application`, {name});
export const submitLeaveApplication = (name) => callMethod(`${NS}.submit_leave_application`, {name});
export const cancelLeaveApplication = (name) => callMethod(`${NS}.cancel_leave_application`, {name});
export const getLeaveEmployees = () => callMethod(`${NS}.get_employees`);
export const getLeaveEmployeeDetails = (employee) => callMethod(`${NS}.get_employee_details`, {employee});
export const getLeaveTypes = (employee,date) => callMethod(`${NS}.get_leave_types`, {employee,date});
export const getAllocatedLeaves = (employee,date) => callMethod(`${NS}.get_allocated_leaves`, {employee,date});
export const getLeaveApplicationSettings = () => callMethod(`${NS}.get_leave_application_settings`);
export const getLeaveBalance = (employee,leave_type,date,to_date) => callMethod(`${NS}.get_leave_balance`, {employee,leave_type,date,to_date});
export const getTotalLeaveDays = (employee,leave_type,from_date,to_date,half_day=0,half_day_date) => callMethod(`${NS}.get_total_leave_days`, {employee,leave_type,from_date,to_date,half_day,half_day_date});
export const getLeaveAllocationPeriod = (employee,leave_type,from_date,to_date) => callMethod(`${NS}.get_allocation_period`, {employee,leave_type,from_date,to_date});
export const getLeaveApprovers = (employee) => callMethod(`${NS}.get_leave_approvers`, {employee});
export const getLeaveCompanies = () => callMethod(`${NS}.get_companies`);
export const getLeaveDepartments = () => callMethod(`${NS}.get_departments`);
export const getLeaveSalarySlips = (employee) => callMethod(`${NS}.get_salary_slips`, {employee});
export const getLeaveLetterHeads = () => callMethod(`${NS}.get_letter_heads`);
export const getLeaveApplicationConnections = (leave_application) => callMethod(`${NS}.get_connections`, {leave_application});
